# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 577)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_first_number = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_first_number.setGeometry(QtCore.QRect(120, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_first_number.setFont(font)
        self.label_first_number.setObjectName("label_first_number")
        self.lineEdit_first_number = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_first_number.setGeometry(QtCore.QRect(280, 100, 221, 41))
        self.lineEdit_first_number.setObjectName("lineEdit_first_number")
        self.label_second_number = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_second_number.setGeometry(QtCore.QRect(120, 180, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_second_number.setFont(font)
        self.label_second_number.setObjectName("label_second_number")
        self.lineEdit_second_number = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_second_number.setGeometry(QtCore.QRect(280, 170, 221, 41))
        self.lineEdit_second_number.setObjectName("lineEdit_second_number")
        self.label_result = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(140, 260, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        self.label_result_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_result_display.setGeometry(QtCore.QRect(280, 260, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_result_display.setFont(font)
        self.label_result_display.setText("")
        self.label_result_display.setObjectName("label_result_display")
        self.pushButton_addition = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_addition.setGeometry(QtCore.QRect(30, 390, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_addition.setFont(font)
        self.pushButton_addition.setObjectName("pushButton_addition")

        #step 1 for ADDITION
        #when user clicks on the addition button, excute the command
        self.pushButton_addition.clicked.connect(self.addition)

        self.pushButton_subtraction = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_subtraction.setGeometry(QtCore.QRect(220, 390, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_subtraction.setFont(font)
        self.pushButton_subtraction.setObjectName("pushButton_subtraction")

        # STEP 1 button for SUBTRACTION
        self.pushButton_subtraction.clicked.connect(self.subtraction)

        self.pushButton_multiply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_multiply.setGeometry(QtCore.QRect(410, 390, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setObjectName("pushButton_multiply")

        # BUTTON for MULTIPLY
        self.pushButton_multiply.clicked.connect(self.multiply)

        self.pushButton_divide = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_divide.setGeometry(QtCore.QRect(600, 390, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setObjectName("pushButton_divide")


        # BUTTON for DIVIDE
        self.pushButton_divide.clicked.connect(self.divide)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_first_number.setText(_translate("MainWindow", "First Number"))
        self.label_second_number.setText(_translate("MainWindow", "Second Number"))
        self.label_result.setText(_translate("MainWindow", "Result"))
        self.pushButton_addition.setText(_translate("MainWindow", "Addition"))
        self.pushButton_subtraction.setText(_translate("MainWindow", "Subtraction"))
        self.pushButton_multiply.setText(_translate("MainWindow", "Multiply"))
        self.pushButton_divide.setText(_translate("MainWindow", "Divide"))

    # function for addition
    #step 2
    def addition(self):
        # step 3 accpet user's input
        self.first_number = self.lineEdit_first_number.text()
        self.second_number = self.lineEdit_second_number.text()
        print("Accepted input from user:", self.first_number, self.second_number)

        # step 4 --> calculate the result
        addition_result = float(self.first_number) + float(self.second_number)
        print("Result of adding user input: ", addition_result)

        #step 5 --> display result
        self.label_result.setText(str(addition_result))

    #function for subtraction
    def subtraction(self):
        self.first_number = self.lineEdit_first_number.text()
        self.second_number = self.lineEdit_second_number.text()
        print("Accepted input from user:", self.first_number, self.second_number)

        subtraction_result = float(self.first_number) - float(self.second_number)
        print("Result of subtraction user input: ", subtraction_result)

        self.label_result.setText(str(subtraction_result))

    #function for multiply
    def multiply(self):
        self.first_number = self.lineEdit_first_number.text()
        self.second_number = self.lineEdit_second_number.text()
        print("Accepted input from user:", self.first_number, self.second_number)

        multiplication_result = float(self.first_number) * float(self.second_number)
        print("Result of multiplication user input: ", multiplication_result)

        self.label_result.setText(str(multiplication_result))

    #function for DIVIDE
    def divide(self):
        self.first_number = self.lineEdit_first_number.text()
        self.second_number = self.lineEdit_second_number.text()
        print("Accepted input from user:", self.first_number, self.second_number)

        division_result = float(self.first_number) / float(self.second_number)
        print("Result of division user input: ", division_result)

        self.label_result.setText(str(division_result))

if __name__ == '__main__':
    import sys
    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())