# Form implementation generated from reading ui file 'Coffee_shop.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_shop_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_shop_name.setGeometry(QtCore.QRect(150, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_shop_name.setFont(font)
        self.label_shop_name.setObjectName("label_shop_name")
        self.label_lattes = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_lattes.setGeometry(QtCore.QRect(150, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_lattes.setFont(font)
        self.label_lattes.setObjectName("label_lattes")
        self.label_cappuccinos = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cappuccinos.setGeometry(QtCore.QRect(150, 190, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_cappuccinos.setFont(font)
        self.label_cappuccinos.setObjectName("label_cappuccinos")
        self.label_espressos = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_espressos.setGeometry(QtCore.QRect(150, 230, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_espressos.setFont(font)
        self.label_espressos.setObjectName("label_espressos")
        self.lineEdit_num_lattes = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_num_lattes.setGeometry(QtCore.QRect(310, 150, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.lineEdit_num_lattes.setFont(font)
        self.lineEdit_num_lattes.setObjectName("lineEdit_num_lattes")
        self.lineEdit_num_cappuccinos = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_num_cappuccinos.setGeometry(QtCore.QRect(310, 190, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.lineEdit_num_cappuccinos.setFont(font)
        self.lineEdit_num_cappuccinos.setObjectName("lineEdit_num_cappuccinos")
        self.lineEdit_num_espressos = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_num_espressos.setGeometry(QtCore.QRect(310, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.lineEdit_num_espressos.setFont(font)
        self.lineEdit_num_espressos.setObjectName("lineEdit_num_espressos")
        self.label_size = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_size.setGeometry(QtCore.QRect(150, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_size.setFont(font)
        self.label_size.setObjectName("label_size")
        self.lineEdit_size = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_size.setGeometry(QtCore.QRect(310, 270, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.lineEdit_size.setFont(font)
        self.lineEdit_size.setObjectName("lineEdit_size")
        self.label_price_latte = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_price_latte.setGeometry(QtCore.QRect(470, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_price_latte.setFont(font)
        self.label_price_latte.setObjectName("label_price_latte")
        self.label_price_cap = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_price_cap.setGeometry(QtCore.QRect(470, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_price_cap.setFont(font)
        self.label_price_cap.setObjectName("label_price_cap")
        self.label_price_espresso = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_price_espresso.setGeometry(QtCore.QRect(470, 240, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_price_espresso.setFont(font)
        self.label_price_espresso.setObjectName("label_price_espresso")
        self.label_price_espresso_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_price_espresso_2.setGeometry(QtCore.QRect(470, 280, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_price_espresso_2.setFont(font)
        self.label_price_espresso_2.setObjectName("label_price_espresso_2")
        self.pushButton_order = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_order.setGeometry(QtCore.QRect(320, 332, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.pushButton_order.setFont(font)
        self.pushButton_order.setObjectName("pushButton_order")

        self.pushButton_order.clicked.connect(self.order)

        self.label_total_cost = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_total_cost.setGeometry(QtCore.QRect(200, 400, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_total_cost.setFont(font)
        self.label_total_cost.setObjectName("label_total_cost")
        self.label_total_cost_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_total_cost_display.setGeometry(QtCore.QRect(290, 400, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_total_cost_display.setFont(font)
        self.label_total_cost_display.setText("")
        self.label_total_cost_display.setObjectName("label_total_cost_display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_shop_name.setText(_translate("MainWindow", "Coffee Shop"))
        self.label_lattes.setText(_translate("MainWindow", "Number of Lattes"))
        self.label_cappuccinos.setText(_translate("MainWindow", "Number of Cappuccinos"))
        self.label_espressos.setText(_translate("MainWindow", "Number of Espressos"))
        self.label_size.setText(_translate("MainWindow", "Size"))
        self.label_price_latte.setText(_translate("MainWindow", "$4.50"))
        self.label_price_cap.setText(_translate("MainWindow", "$5.00"))
        self.label_price_espresso.setText(_translate("MainWindow", "$5.50"))
        self.label_price_espresso_2.setText(_translate("MainWindow", "Small/ Large"))
        self.pushButton_order.setText(_translate("MainWindow", "Order"))
        self.label_total_cost.setText(_translate("MainWindow", "Total Cost:"))

    #'Order' button that, when clicked, calculates the total cost.
    def order(self):


        lattes = self.lineEdit_num_lattes.text()
        print("Number of Lattes:", lattes)
        cappuccinos = self.lineEdit_num_cappuccinos.text()
        print("Number of Cappuccinos:", cappuccinos)
        espressos = self.lineEdit_num_espressos.text()
        print("Number of Espressos:", espressos)
        size = self.lineEdit_size.text()
        print("Size:", size)

        if len(lattes) == 0 or  lattes.isalpha() or len(cappuccinos) == 0 or cappuccinos.isalpha() or len(espressos) == 0 or espressos.isalpha():
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter a valid number of drinks.")
            msg.exec()
        else:
            lattes = int(lattes)
            cappuccinos = int(cappuccinos)
            espressos = int(espressos)

            if size == "small" or size == "Small" or size == "S" or size == "s":
                # Latte: $4.50
                # Cappuccino: $5.00
                # Espresso: $5.50

                # Small -  If the size entered is “Small” then no additional charges apply
                # multiplying the number of coffees for each category with the cost
                # for each coffee type
                cost_lattes = 4.50 * lattes
                print("\ncost for latte:", cost_lattes)
                cost_cappuccinos = 5.00 * cappuccinos
                print("cost for cappuccino:", cost_cappuccinos)
                cost_espresso = 5.50 * espressos
                print("cost for espresso:", cost_espresso)
                cost = cost_lattes + cost_cappuccinos + cost_espresso
                print("total cost:", float(cost))
                # display the total cost calculated
                self.label_total_cost_display.setText(str(cost))
            elif size == "large" or size == "Large" or size == "L" or size == "l":
                # large -  If # the size entered is “Large”,
                # add a $2 surcharge for each coffee
                sub_charge = 2
                # Total cost = (cost × L) + (2 × L)
                cost_lattes = 4.50 * lattes + (lattes * sub_charge)
                print("\ncost for latte:", cost_lattes)
                cost_cappuccinos = 5.0 * cappuccinos + (cappuccinos * sub_charge)
                print("cost for cappuccino:", cost_cappuccinos)
                cost_espresso = 5.50 * int(espressos) + (espressos * sub_charge)
                print("cost for espresso:", cost_espresso)
                cost = cost_lattes + cost_cappuccinos + cost_espresso
                print("total cost:", float(cost))
                # display the total cost calculated
                self.label_total_cost_display.setText(str(cost))
            else:
                msg = QtWidgets.QMessageBox()
                msg.setText("Please enter valid size.")
                msg.exec()



if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())