# Form implementation generated from reading ui file 'database_retrieve_inclass.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import pymysql

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(160, 100, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 230, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(160, 160, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_age = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_age.setGeometry(QtCore.QRect(160, 220, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_age.setFont(font)
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.pushButton_insert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_insert.setGeometry(QtCore.QRect(60, 310, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_insert.setFont(font)
        self.pushButton_insert.setObjectName("pushButton_insert")

        self.pushButton_insert.clicked.connect(self.insert_data)

        self.pushButton_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(220, 310, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.pushButton_clear.clicked.connect(self.clear)

        self.pushButton_display = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_display.setGeometry(QtCore.QRect(490, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_display.setFont(font)
        self.pushButton_display.setObjectName("pushButton_display")

        self.pushButton_display.clicked.connect(self.display)

        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(380, 70, 401, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student Id"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Age"))
        self.pushButton_insert.setText(_translate("MainWindow", "Insert"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_display.setText(_translate("MainWindow", "Display Data"))

    #write code for clear button -- clear function
    def clear(self):
        self.lineEdit_id.clear()
        self.lineEdit_name.clear()
        self.lineEdit_age.clear()
        self.tableWidget.clearContents()

    #write code for display button  -- display function
    def display(self):
        try:
            print("in the function display")

            # establish connection to the database
            self.establish_connection()

            # define a cursor --> allows us to iterate over the result
            cursor = self.connection.cursor()
            cursor.execute("select * from student.student_table;")
            resultset = cursor.fetchall()  # gets all rows from the SELECT * execution
            print("result set output", resultset)

            columns = []
            for col in cursor.description:
                columns.append(col[0])
                print(col, columns)

            self.tableWidget.setColumnCount(len(columns))  # add the number of columns to the table as many as the length

            self.tableWidget.setHorizontalHeaderLabels(columns)

            self.tableWidget.setRowCount(0)  # set the number of rowd to be 0
            print("table is set")
            for record in resultset:
                print("row in resultset", record)
                rows = self.tableWidget.rowCount()
                self.tableWidget.insertRow(rows)
                self.tableWidget.setItem(rows, 0, QtWidgets.QTableWidgetItem(str(record[0])))
                self.tableWidget.setItem(rows, 1, QtWidgets.QTableWidgetItem(str(record[1])))
                self.tableWidget.setItem(rows, 2, QtWidgets.QTableWidgetItem(str(record[2])))
        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not display to table" + str(e))
            msg.exec()

    def establish_connection(self):
        try:
            self.connection = pymysql.connect(
                host="localhost",
                database="student",
                user="bus442",
                password="bus442")


            msg = QtWidgets.QMessageBox()
            msg.setText("Connection established")
            msg.exec()
        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not close conection to the database" + str(e))
            msg.exec()

    def close_connection(self):
       try:
           self.connection.close()
       except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not close conection to the database" + str(e))
            msg.exec()

    def insert_data(self):
        #userr import validation
        if len(self.lineEdit_id.text()) > 0 and len(self.lineEdit_name.text()) > 0 and len(self.lineEdit_age.text()) > 0:
            print("Uer input acceptable")

            if self.lineEdit_id.text().isdigit() and self.lineEdit_age.text().isdigit():
                print("User's input verified")

                self.establish_connection() # establish connection to the databse
                self.cursor = self.connection.cursor()  # create cursor
                self.cursor.execute("select * from student.student_table;")
                resultset = self.cursor.fetchall()

                check_student_id = 0


                for record in resultset:
                    print(record)
                    if record[0] == int(self.lineEdit_id.text()):
                        check_student_id = 1
                        print("Check of student id exists --> yes" )

                # insert new record in table
                if check_student_id == 0:
                    print('trying to insert record')
                    query = "INSERT INTO student_table VALUES (%s, %s, %s)"

                    arguments = (int(self.lineEdit_id.text()),
                                 self.lineEdit_name.text(),
                                 int(self.lineEdit_age.text()))
                    print(query, arguments)

                    self.cursor.execute(query, arguments)   #eecute the query
                    self.connection.commit()

                    msg = QtWidgets.QMessageBox()
                    msg.setText("Record added successfully")
                    msg.exec()
                else:
                    msg = QtWidgets.QMessageBox()
                    msg.setText("Student id already exists")
                    msg.exec()

            else:
                msg = QtWidgets.QMessageBox()
                msg.setText("Please ensure numeric inputs for ID and age")
                msg.exec()



        else:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter a valid input")
            msg.exec()


if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())