# Form implementation generated from reading ui file 'Financial_calculator_for_loop.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_contribution = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_contribution.setGeometry(QtCore.QRect(70, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_contribution.setFont(font)
        self.label_contribution.setObjectName("label_contribution")
        self.label_years = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_years.setGeometry(QtCore.QRect(70, 100, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_years.setFont(font)
        self.label_years.setObjectName("label_years")
        self.lineEdit_contribution = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_contribution.setGeometry(QtCore.QRect(210, 50, 161, 41))
        self.lineEdit_contribution.setObjectName("lineEdit_contribution")
        self.lineEdit_years = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_years.setGeometry(QtCore.QRect(210, 100, 161, 41))
        self.lineEdit_years.setObjectName("lineEdit_years")
        self.checkBox_generate = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_generate.setGeometry(QtCore.QRect(120, 170, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_generate.setFont(font)
        self.checkBox_generate.setObjectName("checkBox_generate")
        self.pushButton_generate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_generate.setGeometry(QtCore.QRect(100, 230, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_generate.setFont(font)
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.pushButton_generate.clicked.connect(self.generate)

        self.pushButton_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(60, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_clear.clicked.connect(self.clear)

        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(260, 310, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_exit.clicked.connect(self.exit)

        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(410, 40, 331, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_contribution.setText(_translate("MainWindow", "Annual Contribution"))
        self.label_years.setText(_translate("MainWindow", "Number of Years"))
        self.checkBox_generate.setText(_translate("MainWindow", "Retirement Plan 2050"))
        self.pushButton_generate.setText(_translate("MainWindow", "Generate Portfolio"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Year"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Portfolio Balance"))

    def exit(self):
        application.exit()


    def clear(self):
        # clear input
        self.lineEdit_contribution.clear()
        self.lineEdit_years.clear()
        self.checkBox_generate.setChecked(False)
        self.tableWidget.setRowCount(0)


    def generate(self):

        #step 1 accept annual  contribution
        if len(self.lineEdit_contribution.text()) == 0:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter annual contribution amount")
            msg.exec()
            return None

        #step 2 check for empty years
        if len(self.lineEdit_years.text()) == 0:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter number of years")
            msg.exec()
            return None

        annual_contribution = float(self.lineEdit_contribution.text()) #accept yearly contribution
        total_years = int(self.lineEdit_years.text())   #access number of years
        retirement_plan = self.checkBox_generate.isChecked()
        print("User's input:", annual_contribution, total_years, retirement_plan)


        if retirement_plan: #true or false
            rate_of_return = 7.8 # checkbox is checked
        else:
            rate_of_return = 5.0

        portfolio_value = 0 #value of portfolio at the end of each year
        # for each year
        for year in range(1, total_years + 1):
            portfolio_value = (portfolio_value + annual_contribution) * (1 + rate_of_return/100) #portfolio value
            print(year, annual_contribution, rate_of_return, portfolio_value)

            row_count = self.tableWidget.rowCount()         #get the number if rows in the tablewidget
            self.tableWidget.insertRow(row_count)
            self.tableWidget.setItem(row_count, 0, QtWidgets.QTableWidgetItem(str(year))) #insert year in column o
            self.tableWidget.setItem(row_count, 1, QtWidgets.QTableWidgetItem(str(portfolio_value)))

if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())
