# Form implementation generated from reading ui file 'Financial_calculator_while_loop.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_contribution = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_contribution.setGeometry(QtCore.QRect(170, 50, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_contribution.setFont(font)
        self.label_contribution.setObjectName("label_contribution")
        self.lineEdit_contribution = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_contribution.setGeometry(QtCore.QRect(370, 40, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_contribution.setFont(font)
        self.lineEdit_contribution.setObjectName("lineEdit_contribution")
        self.label_target = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_target.setGeometry(QtCore.QRect(210, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_target.setFont(font)
        self.label_target.setObjectName("label_target")
        self.lineEdit_target = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_target.setGeometry(QtCore.QRect(370, 100, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_target.setFont(font)
        self.lineEdit_target.setObjectName("lineEdit_target")
        self.label_plan = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_plan.setGeometry(QtCore.QRect(210, 190, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_plan.setFont(font)
        self.label_plan.setObjectName("label_plan")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(380, 190, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")

        #
        self.comboBox.addItems(["Retirement Plan 2050", "Retirement Plan 2060"])

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 280, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.calculate_years)

        self.label_output = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(160, 390, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_output.setFont(font)
        self.label_output.setWordWrap(True)
        self.label_output.setObjectName("label_output")
        self.label_output_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_output_display.setGeometry(QtCore.QRect(420, 390, 241, 61))
        self.label_output_display.setText("")
        self.label_output_display.setObjectName("label_output_display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_contribution.setText(_translate("MainWindow", "Annual Contribution"))
        self.label_target.setText(_translate("MainWindow", "Target Balance"))
        self.label_plan.setText(_translate("MainWindow", "Retirement Plan"))
        self.pushButton.setText(_translate("MainWindow", "How Long?"))
        self.label_output.setText(_translate("MainWindow", "Number of Years to reach target balance"))


    def calculate_years(self):
        #step 0 --> user input validation --> len(input) == 0 --> message

        #step 1: accept user's input
        annual_contribution = float(self.lineEdit_contribution.text())
        target_balance = float(self.lineEdit_target.text())

        selected_plan = self.comboBox.currentIndex() #user selection from combo box
        print("User input", annual_contribution, target_balance, selected_plan)

        rate_of_return = 0.0
        if selected_plan == "Retirement Plan 2050":
            rate_of_return = 5.0
        elif selected_plan == "Retirement Plan 2060":
            rate_of_return = 6.0

        portfolio_balance = 0
        number_of_years = 0

        while portfolio_balance < target_balance:   #stop when the portfolio is => target balance
            portfolio_balance = (portfolio_balance + annual_contribution) +(1+rate_of_return/100)
            number_of_years = number_of_years + 1
            print(number_of_years, portfolio_balance)

        self.label_output_display.setText(str(number_of_years))

if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())