# Form implementation generated from reading ui file 'gymMembershipCalculator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 598)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_FName = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_FName.setGeometry(QtCore.QRect(120, 40, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_FName.setFont(font)
        self.label_FName.setObjectName("label_FName")
        self.label_LName = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_LName.setGeometry(QtCore.QRect(120, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_LName.setFont(font)
        self.label_LName.setObjectName("label_LName")
        self.lineEdit_FName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_FName.setGeometry(QtCore.QRect(270, 30, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_FName.setFont(font)
        self.lineEdit_FName.setObjectName("lineEdit_FName")
        self.lineEdit_LName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_LName.setGeometry(QtCore.QRect(270, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_LName.setFont(font)
        self.lineEdit_LName.setObjectName("lineEdit_LName")
        self.label_age = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_age.setGeometry(QtCore.QRect(170, 150, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_age.setFont(font)
        self.label_age.setObjectName("label_age")
        self.lineEdit_age = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_age.setGeometry(QtCore.QRect(270, 150, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_age.setFont(font)
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(270, 210, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label_plan = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_plan.setGeometry(QtCore.QRect(100, 210, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_plan.setFont(font)
        self.label_plan.setObjectName("label_plan")
        self.checkBox_discount = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_discount.setGeometry(QtCore.QRect(490, 210, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_discount.setFont(font)
        self.checkBox_discount.setObjectName("checkBox_discount")
        self.pushButton_calculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(220, 280, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_calculate.setFont(font)
        self.pushButton_calculate.setObjectName("pushButton_calculate")

        # code for calculate button
        self.pushButton_calculate.clicked.connect(self.calculate_fee)

        self.pushButton_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(640, 450, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")

        # code for clear button
        self.pushButton_clear.clicked.connect(self.clear)

        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(640, 513, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")

        # code for exit button
        self.pushButton_exit.clicked.connect(self.exit)

        self.label_display_first_month = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_display_first_month.setGeometry(QtCore.QRect(240, 380, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_display_first_month.setFont(font)
        self.label_display_first_month.setText("")
        self.label_display_first_month.setObjectName("label_display_first_month")
        self.label_first_month_fee = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_first_month_fee.setGeometry(QtCore.QRect(50, 380, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_first_month_fee.setFont(font)
        self.label_first_month_fee.setObjectName("label_first_month_fee")
        self.label_display_after_first_month = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_display_after_first_month.setGeometry(QtCore.QRect(240, 440, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_display_after_first_month.setFont(font)
        self.label_display_after_first_month.setText("")
        self.label_display_after_first_month.setObjectName("label_display_after_first_month")
        self.label_after_first_month = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_after_first_month.setGeometry(QtCore.QRect(50, 440, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_after_first_month.setFont(font)
        self.label_after_first_month.setObjectName("label_after_first_month")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # create a list for the combo box to allow members to select their preferred plan. This
        # dropdown should include four options ("Basic", "Standard", "Premium", "Family
        self.plan = ["", "Basic", "Standard", "Premium", "Family"]
        # to add to combobox:
        self.comboBox.addItems(self.plan)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_FName.setText(_translate("MainWindow", "First Name:"))
        self.label_LName.setText(_translate("MainWindow", "Last Name:"))
        self.label_age.setText(_translate("MainWindow", "Age:"))
        self.label_plan.setText(_translate("MainWindow", "Preffered Plan:"))
        self.checkBox_discount.setText(_translate("MainWindow", "Student discount (20%)"))
        self.pushButton_calculate.setText(_translate("MainWindow", "Calculate Fee"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear Form"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        self.label_first_month_fee.setText(_translate("MainWindow", "First Month Fee:"))
        self.label_after_first_month.setText(_translate("MainWindow", "After First Month:"))

    # Exit Functionality: close the application
    def exit(self):
        application.exit()

    # Resetting Form:
    #- A button labeled "Clear Form" should reset all fields to their default values, allowing for a new entry.
    def clear(self):
        # clear input
        self.lineEdit_FName.clear()
        self.lineEdit_LName.clear()
        self.lineEdit_age.clear()
        self.comboBox.setCurrentIndex(-1)
        self.checkBox_discount.setChecked(False)

        # clear application output
        self.label_display_first_month.clear()
        self.label_display_after_first_month.clear()

    #application should calculate the fee based on the selected plan and student discount.
    """  Include a button labeled "Calculate Fee". When clicked, the application should calculate the
        fee based on the selected plan and student discount. """

    def calculate_fee(self):
        # Collect the member’s First Name, Last Name, and Age
        fname = self.lineEdit_FName.text()
        lname = self.lineEdit_LName.text()
        age = self.lineEdit_age.text()
        print(fname, lname, age)

        # Use a combo box (dropdown) to allow members to select their preferred plan
        selected_plan = self.comboBox.currentText()
        print(selected_plan)

        #Use a check box labeled “Student discount (20%)” for students
        student_discount = self.checkBox_discount.isChecked()

        """
        Base monthly fee:
               - Basic: $30
               - Standard: $45
               - Premium: $60
               - Family: $80
               Facility fees (One-time payment): $20
               The total fee for the first month is a combination of the base fee and facility fee and the 20% student
               discount on the base fee if the check box is selected. The total fee for each month after the first month
               is the base fee plus the 20% student discount on the base fee if the check box is selected
        """
        base_price = 30
        standard_price = 45
        premium_price = 60
        family_price = 80
        facility_price = 20
        price = 0


        if student_discount:  #true or false
            discount = .20 # “Student discount (20%)”
            if selected_plan == "Basic":
                # first monthly fee: base price - (base fee * discount ) + facility fee
                #      ( 30  -  (30  * .2 ))   +       20  = 44
                discount_price = int(base_price - (base_price * discount))       # to show as an int without decimal
                price = discount_price + facility_price
                #print(price)
                #Display first month fee
                self.label_display_first_month.setText(str(price))
                # Display monthly fee after first month
                # month after first = base fee
                self.label_display_after_first_month.setText(str(discount_price))
            elif selected_plan == "Standard":
                discount_price = int(standard_price - (standard_price * discount))
                price = discount_price + facility_price
                #print(price)
                # Display first month fee
                self.label_display_first_month.setText(str(price))

                # month after first = base fee
                self.label_display_after_first_month.setText(str(discount_price))
            elif selected_plan == "Premium":
                discount_price = int(premium_price - (premium_price * discount))
                price = discount_price + facility_price
                #print(price)
                # Display first month fee
                self.label_display_first_month.setText(str(price))

                self.label_display_after_first_month.setText(str(discount_price))
            else:
                discount_price = int(family_price - (family_price * discount))
                price = discount_price + facility_price
                #print(price)
                # Display first month fee
                self.label_display_first_month.setText(str(price))
                self.label_display_after_first_month.setText(str(discount_price))
        else:

            if selected_plan == "Basic":
                # first monthly fee: base fee  + facility fee
                #       30          +       20  = 50
                price = base_price + facility_price
                #print(price)
                # Display first month fee
                self.label_display_first_month.setText(str(price))

                # month after first = base fee
                self.label_display_after_first_month.setText(str(base_price))
            elif selected_plan == "Standard":
                #       45              + 20    = 65
                price = standard_price + facility_price
                #print(price)
                self.label_display_first_month.setText(str(price))

                # month after first = base fee
                self.label_display_after_first_month.setText(str(standard_price))
            elif selected_plan == "Premium":
                #       60            +     20      = 80
                price = premium_price + facility_price
                #print(price)
                self.label_display_first_month.setText(str(price))

                self.label_display_after_first_month.setText(str(premium_price))
            else:
                #       80          +       20      = 100
                price = family_price + facility_price
                #print(price)
                self.label_display_first_month.setText(str(price))
                self.label_display_after_first_month.setText(str(family_price))

if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())