# Form implementation generated from reading ui file 'Home_purchase.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 559)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 40, 911, 461))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_home_purchase = QtWidgets.QWidget()
        self.tab_home_purchase.setObjectName("tab_home_purchase")
        self.label_name = QtWidgets.QLabel(parent=self.tab_home_purchase)
        self.label_name.setGeometry(QtCore.QRect(60, 30, 121, 31))
        self.label_name.setObjectName("label_name")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.tab_home_purchase)
        self.lineEdit_name.setGeometry(QtCore.QRect(180, 30, 151, 31))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_age = QtWidgets.QLineEdit(parent=self.tab_home_purchase)
        self.lineEdit_age.setGeometry(QtCore.QRect(180, 70, 151, 31))
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.label_age = QtWidgets.QLabel(parent=self.tab_home_purchase)
        self.label_age.setGeometry(QtCore.QRect(80, 70, 121, 31))
        self.label_age.setObjectName("label_age")
        self.label_house_type = QtWidgets.QLabel(parent=self.tab_home_purchase)
        self.label_house_type.setGeometry(QtCore.QRect(90, 110, 121, 31))
        self.label_house_type.setObjectName("label_house_type")
        self.comboBox = QtWidgets.QComboBox(parent=self.tab_home_purchase)
        self.comboBox.setGeometry(QtCore.QRect(180, 110, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab_home_purchase)
        self.groupBox.setGeometry(QtCore.QRect(190, 150, 131, 111))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_standard = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_standard.setGeometry(QtCore.QRect(10, 20, 131, 30))
        self.radioButton_standard.setObjectName("radioButton_standard")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_standard)
        self.radioButton_smart = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_smart.setGeometry(QtCore.QRect(10, 50, 131, 30))
        self.radioButton_smart.setObjectName("radioButton_smart")
        self.buttonGroup.addButton(self.radioButton_smart)
        self.radioButton_luxury = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_luxury.setGeometry(QtCore.QRect(10, 80, 111, 30))
        self.radioButton_luxury.setObjectName("radioButton_luxury")
        self.buttonGroup.addButton(self.radioButton_luxury)
        self.label_down_payment = QtWidgets.QLabel(parent=self.tab_home_purchase)
        self.label_down_payment.setGeometry(QtCore.QRect(50, 270, 141, 31))
        self.label_down_payment.setObjectName("label_down_payment")
        self.lineEdit_down_payment = QtWidgets.QLineEdit(parent=self.tab_home_purchase)
        self.lineEdit_down_payment.setGeometry(QtCore.QRect(190, 270, 151, 31))
        self.lineEdit_down_payment.setObjectName("lineEdit_down_payment")
        self.pushButton_purchase = QtWidgets.QPushButton(parent=self.tab_home_purchase)
        self.pushButton_purchase.setGeometry(QtCore.QRect(260, 380, 151, 34))
        self.pushButton_purchase.setObjectName("pushButton_purchase")

        self.pushButton_purchase.clicked.connect(self.purchases_made)

        self.pushButton_show_payments = QtWidgets.QPushButton(parent=self.tab_home_purchase)
        self.pushButton_show_payments.setGeometry(QtCore.QRect(90, 380, 151, 34))
        self.pushButton_show_payments.setObjectName("pushButton_show_payments")

        self.pushButton_show_payments.clicked.connect(self.show_payments)

        self.pushButton_exit = QtWidgets.QPushButton(parent=self.tab_home_purchase)
        self.pushButton_exit.setGeometry(QtCore.QRect(570, 380, 114, 34))
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.pushButton_exit.clicked.connect(self.exit)

        self.pushButton_clear = QtWidgets.QPushButton(parent=self.tab_home_purchase)
        self.pushButton_clear.setGeometry(QtCore.QRect(430, 380, 114, 34))
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.pushButton_clear.clicked.connect(self.clear)

        self.tableWidget_monthly_payment = QtWidgets.QTableWidget(parent=self.tab_home_purchase)
        self.tableWidget_monthly_payment.setGeometry(QtCore.QRect(390, 10, 511, 251))
        self.tableWidget_monthly_payment.setObjectName("tableWidget_monthly_payment")
        self.tableWidget_monthly_payment.setColumnCount(3)
        self.tableWidget_monthly_payment.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monthly_payment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monthly_payment.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monthly_payment.setHorizontalHeaderItem(2, item)
        self.tabWidget.addTab(self.tab_home_purchase, "")
        self.tab_purchases_made = QtWidgets.QWidget()
        self.tab_purchases_made.setObjectName("tab_purchases_made")
        self.tableWidget_purchase_made = QtWidgets.QTableWidget(parent=self.tab_purchases_made)
        self.tableWidget_purchase_made.setGeometry(QtCore.QRect(80, 30, 631, 281))
        self.tableWidget_purchase_made.setObjectName("tableWidget_purchase_made")
        self.tableWidget_purchase_made.setColumnCount(5)
        self.tableWidget_purchase_made.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_purchase_made.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_purchase_made.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_purchase_made.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_purchase_made.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_purchase_made.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_purchases_made, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        # create a list for the combo box to allow customers to select their house type
        # This dropdown should include four options
        # ("Apartment", "Townhouse", "Single-Family Home", "Luxury Villa")
        self.house_selection = ["", "Apartment", "Townhouse", "Single-Family House", "Luxury Villa"]
        # to add to combobox:
        self.comboBox.addItems(self.house_selection)

        self.house_prices = {}

        self.all_purchases = {}

        self.tabWidget.tabBarClicked.connect(self.display_purchases)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Customer\'s Name:"))
        self.label_age.setText(_translate("MainWindow", "Customer Age:"))
        self.label_house_type.setText(_translate("MainWindow", "House Type:"))
        self.groupBox.setTitle(_translate("MainWindow", "Model Type"))
        self.radioButton_standard.setText(_translate("MainWindow", "Standard"))
        self.radioButton_smart.setText(_translate("MainWindow", "Smart"))
        self.radioButton_luxury.setText(_translate("MainWindow", "Luxury"))
        self.label_down_payment.setText(_translate("MainWindow", "Inital Down Payment:"))
        self.pushButton_purchase.setText(_translate("MainWindow", "Purchase"))
        self.pushButton_show_payments.setText(_translate("MainWindow", "Show Payments"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        item = self.tableWidget_monthly_payment.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Month Number"))
        item = self.tableWidget_monthly_payment.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Monthly Payment"))
        item = self.tableWidget_monthly_payment.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Remaining Balance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_home_purchase), _translate("MainWindow", "Home Purchase"))
        item = self.tableWidget_purchase_made.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_purchase_made.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Age"))
        item = self.tableWidget_purchase_made.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "House Selected"))
        item = self.tableWidget_purchase_made.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Model Type"))
        item = self.tableWidget_purchase_made.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Down Payment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_purchases_made), _translate("MainWindow", "Purchases Made"))

    # Exit Functionality: close the application
    def exit(self):
        application.exit()

    # - A button labeled "Clear Form" should reset all fields to their default values, allowing for a new entry.
    def clear(self):
        # clear input
        self.lineEdit_name.clear()
        self.lineEdit_age.clear()
        self.lineEdit_down_payment.clear()
        self.comboBox.setCurrentIndex(-1)
        self.buttonGroup.setExclusive(False)
        self.radioButton_standard.setChecked(False)
        self.radioButton_smart.setChecked(False)
        self.radioButton_luxury.setChecked(False)

    def purchases_made(self):
        print("in purchases_made")

        # Button click event for the Purchase button:
        # Accept all the user inputs (Name, age, house selected, model type, down payment).
        # If any of the input fields are not filled/selected display a message to the user using a message box.
        name = self.lineEdit_name.text()
        if len(name) == 0 or not name.isalpha():
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter your name")
            msg.exec()
            return None
        age = self.lineEdit_age.text()
        if len(age) == 0 or age.isalpha():
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter your age")
            msg.exec()
            return None
        house_selected = self.comboBox.currentText()
        if house_selected == "":
            msg = QtWidgets.QMessageBox()
            msg.setText("Please select the house type")
            msg.exec()
            return None
        model_type = self.buttonGroup.checkedButton()
        if self.buttonGroup.checkedButton() == None:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please select model type")
            msg.exec()
            return None
        down_payment = self.lineEdit_down_payment.text()
        if len(down_payment) == 0 or down_payment.isalpha():
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter a valid down payment")
            msg.exec()
            return None

        age = str(age)
        down_payment = str(down_payment)
        model_type = str(self.buttonGroup.checkedButton().text())

        print(name, age, house_selected, model_type, down_payment)

        # adding keys to data to add to dictionary
        if len(self.all_purchases) > 0:
            get_keys = int(max(self.all_purchases.keys()))
            get_keys = get_keys + 1
        else:
            get_keys = 1
        print("new key to be added:", get_keys)

        self.all_purchases[get_keys] = {}
        self.all_purchases[get_keys]["name"] = self.lineEdit_name.text()
        self.all_purchases[get_keys]["age"] = self.lineEdit_age.text()
        self.all_purchases[get_keys]["house selected"] = self.comboBox.currentText()
        self.all_purchases[get_keys]["model type"] = self.buttonGroup.checkedButton().text()
        self.all_purchases[get_keys]["down payment"] = self.lineEdit_down_payment.text()

        self.display_purchases()

        import json
        # open file with intention to write
        ## Write this data to an external file(purchases_made.txt). Each entry should be in a new line.
        with open("C:/Users/amryb/Desktop/ABP/NCSU/BUS 442/In class/purchases_made.json", "w") as file_handler:
            json.dump(self.all_purchases, file_handler)  # write student_data to opened file
        print("data exported")
        msg = QtWidgets.QMessageBox()
        msg.setText("Data exported successfully")
        msg.exec()

    def show_payments(self):
        print("in show_payments")
        ## valiidate even in show payments because otherwise it does not know what to so when no code is typed
        name = self.lineEdit_name.text()
        if len(name) == 0 or not name.isalpha():
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter your name")
            msg.exec()
            return None
        age = self.lineEdit_age.text()
        if len(age) == 0 or age.isalpha():
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter your age")
            msg.exec()
            return None
        house_selected = self.comboBox.currentText()
        if house_selected == "":
            msg = QtWidgets.QMessageBox()
            msg.setText("Please select the house type")
            msg.exec()
            return None
        model_type = self.buttonGroup.checkedButton()
        if self.buttonGroup.checkedButton() == None:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please select model type")
            msg.exec()
            return None
        down_payment = self.lineEdit_down_payment.text()
        if len(down_payment) == 0 or down_payment.isalpha():
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter a valid down payment")
            msg.exec()
            return None

        age = str(age)
        down_payment = str(down_payment)
        model_type = str(self.buttonGroup.checkedButton().text())

        print(name, age, house_selected, model_type, down_payment)
        """
                Button click event for the Show Payment button:

                Calculate monthly payments
                and display the data in a list box.
                Please display Month number,
                Monthly payment and Remaining balance as the three columns.

                The house price is stored in the dictionary you created above.
                You must modify the house price according to the type of mode.

                Add 15% to the price for the Smart model and 20% for the Luxury model.
                Once you determine the total price of the house you can calculate monthly payments.
                """
        ##
        # The house price is stored in the dictionary you created above. You must modify the house
        # price according to the type of mode. ##
        print("Import data")

        # read the json file
        import json
        with open(
                "C:/Users/amryb/Desktop/ABP/NCSU/BUS 442/In class/F25_BUS442_project3_prices.json") as file_handler:
            self.house_prices = json.load(file_handler)

        print("house prices read from the file:", self.house_prices)

        house_type = self.comboBox.currentText()
        print("house type selected by user:", house_type)

        model_type = str(self.buttonGroup.checkedButton().text())
        print("model type selected by user:", model_type)

        down_payment = float(self.lineEdit_down_payment.text())

        house_price = 0

        # Add 15% to the price for the Smart model and 20% for  the Luxury model.
        if house_type == "Apartment":
            print("house type", house_type)
            price = self.house_prices[house_type]

            if model_type == "Smart":
                house_price = price * 1.15
                print(house_type, model_type, house_price)
            elif model_type == "Luxury":
                house_price = price * 1.20
                print(house_type, model_type, house_price)
            else:
                house_price = price
                print(house_type, model_type, house_price)
        elif house_type == "Townhouse":
            print("house type", house_type)
            price = self.house_prices[house_type]

            if model_type == "Smart":
                house_price = price * 1.15
                print(house_type, model_type, house_price)
            elif model_type == "Luxury":
                house_price = price * 1.20
                print(house_type, model_type, house_price)
            else:
                house_price = price
                print(house_type, model_type, house_price)
        elif house_type == "Single-Family House":
            print("house type", house_type)
            price = self.house_prices[house_type]

            if model_type == "Smart":
                house_price = price * 1.15
                print(house_type, model_type, house_price)
            elif model_type == "Luxury":
                house_price = price * 1.20
                print(house_type, model_type, house_price)
            else:
                house_price = price
                print(house_type, model_type, house_price)
        elif house_type == "Luxury Villa":
            print("house type", house_type)
            price = self.house_prices[house_type]

            if model_type == "Smart":
                house_price = price * 1.15
                print(house_type, model_type, house_price)
            elif model_type == "Luxury":
                house_price = price * 1.20
                print(house_type, model_type, house_price)
            else:
                house_price = price
                print(house_type, model_type, house_price)

        loan_amount = house_price - down_payment

        """
        Assume annual_interest_rate = 0.07 and loan_term = 120 months.

        Use the above formula once to compute the fixed monthly payment,
        then iterate month-by-month reducing the balance until it reaches zero.

        To calculate the payments, use the formula below.
        monthly_interest_rate = annual_interest_rate / 12
        loan_amount = house_price – down_payment
        monthly_payment = loan_amount * monthly_rate * (1 + monthly_rate) **
        loan_term_months / ((1 + monthly_rate) ** loan_term_months - 1)

        Display monthly payment until loan_amount is 0.
        """

        annual_interest_rate = 0.07
        loan_term_months = 120
        monthly_interest_rate = annual_interest_rate / 12

        monthly_payment = (loan_amount * monthly_interest_rate * ((1 + monthly_interest_rate) ** loan_term_months))/ (((1 + monthly_interest_rate) ** loan_term_months) - 1)

        self.tableWidget_monthly_payment.setRowCount(0)

        current_balance = house_price - down_payment
        month_number = 0

        while current_balance > 0 and month_number < loan_term_months:
            # interst = current balance * monthly interest rate
            current_interest = current_balance * monthly_interest_rate
            # principal = monthly payment - interest
            principal = monthly_payment - current_interest
            # new balance = current balance - principal
            current_balance = current_balance - principal
            month_number += 1

            row_count = self.tableWidget_monthly_payment.rowCount()
            self.tableWidget_monthly_payment.insertRow(row_count)

            self.tableWidget_monthly_payment.setItem(row_count, 0, QtWidgets.QTableWidgetItem(str(month_number)))
            self.tableWidget_monthly_payment.setItem(row_count, 1, QtWidgets.QTableWidgetItem(f"$ {monthly_payment:.2f}"))
            self.tableWidget_monthly_payment.setItem(row_count, 2, QtWidgets.QTableWidgetItem(f"$ {current_balance:.2f}"))

            print(month_number, monthly_payment, current_balance)

    def display_purchases(self):
        # Read the data from the purchases_made.txt file and display each line to the list box.
        print("in display_purchases")

        self.tableWidget_purchase_made.setRowCount(0)

        for name, purchase in self.all_purchases.items():
            print(name, purchase)
            print(purchase['name'], purchase['age'], purchase['house selected'], purchase['model type'],
                  purchase['down payment'])

            row = self.tableWidget_purchase_made.rowCount()
            self.tableWidget_purchase_made.insertRow(row)

            self.tableWidget_purchase_made.setItem(row, 0, QtWidgets.QTableWidgetItem(purchase['name']))
            self.tableWidget_purchase_made.setItem(row, 1, QtWidgets.QTableWidgetItem(str(purchase['age'])))
            self.tableWidget_purchase_made.setItem(row, 2, QtWidgets.QTableWidgetItem(purchase['house selected']))
            self.tableWidget_purchase_made.setItem(row, 3, QtWidgets.QTableWidgetItem(purchase['model type']))
            self.tableWidget_purchase_made.setItem(row, 4, QtWidgets.QTableWidgetItem(str(purchase['down payment'])))

if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())
