# Form implementation generated from reading ui file 'multiform_finacial_aaplication.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(70, 50, 651, 401))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_annual = QtWidgets.QLabel(parent=self.page)
        self.label_annual.setGeometry(QtCore.QRect(90, 80, 211, 31))
        self.label_annual.setObjectName("label_annual")
        self.label_rate = QtWidgets.QLabel(parent=self.page)
        self.label_rate.setGeometry(QtCore.QRect(130, 130, 191, 31))
        self.label_rate.setObjectName("label_rate")
        self.label_goal = QtWidgets.QLabel(parent=self.page)
        self.label_goal.setGeometry(QtCore.QRect(130, 180, 201, 31))
        self.label_goal.setObjectName("label_goal")
        self.lineEdit_contribution = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_contribution.setGeometry(QtCore.QRect(290, 70, 211, 41))
        self.lineEdit_contribution.setObjectName("lineEdit_contribution")
        self.lineEdit_return_rate = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_return_rate.setGeometry(QtCore.QRect(290, 120, 211, 41))
        self.lineEdit_return_rate.setObjectName("lineEdit_return_rate")
        self.lineEdit_goal = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_goal.setGeometry(QtCore.QRect(290, 170, 211, 41))
        self.lineEdit_goal.setObjectName("lineEdit_goal")
        self.pushButton_compute = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_compute.setGeometry(QtCore.QRect(40, 300, 331, 34))
        self.pushButton_compute.setObjectName("pushButton_compute")

        self.pushButton_compute.clicked.connect(self.calculate_years)

        self.pushButton_exit = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_exit.setGeometry(QtCore.QRect(420, 300, 114, 34))
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.pushButton_exit.clicked.connect(self.exit_application)

        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(60, 30, 491, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.pushButton_close = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_close.setGeometry(QtCore.QRect(240, 260, 114, 34))
        self.pushButton_close.setObjectName("pushButton_close")

        self.pushButton_close.clicked.connect(self.close_form)

        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_annual.setText(_translate("MainWindow", "Annual Contribution"))
        self.label_rate.setText(_translate("MainWindow", "Rate of Return"))
        self.label_goal.setText(_translate("MainWindow", "Financial Goal"))
        self.pushButton_compute.setText(_translate("MainWindow", "How long to reach financial goal?"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Year"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Account Balanace"))
        self.pushButton_close.setText(_translate("MainWindow", "Close"))

    def exit_application(self):
        application.quit()

        # code when user clicks on the "How many years"

    def calculate_years(self):
        print("in calculate_years function")
        if self.lineEdit_contribution.text() == "" or self.lineEdit_goal.text() == "" or self.lineEdit_return_rate.text() == "":
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter all inputs")
            msg.exec()
            return None

        if self.lineEdit_contribution.text().isdigit() and self.lineEdit_goal.text().isdigit() and self.lineEdit_return_rate.text().isdigit():
            print("user input is valid")
            # accept user's inputs
            annual_contribution = float(self.lineEdit_contribution.text())
            return_rate = float(self.lineEdit_return_rate.text())
            finacial_goal = float(self.lineEdit_goal.text())

            self.stackedWidget.setCurrentIndex(1)

            current_balance = 0
            current_year = 0

            while current_balance < finacial_goal:
                current_balance = (current_balance + annual_contribution) * (1 + return_rate / 100)
                current_year += 1

                row_count = self.tableWidget.rowCount()
                self.tableWidget.insertRow(row_count)

                self.tableWidget.setItem(row_count, 0, QtWidgets.QTableWidgetItem(str(current_year)))
                self.tableWidget.setItem(row_count, 1, QtWidgets.QTableWidgetItem(str(current_balance)))

                print(current_year, current_balance)

        else:  # user input is not digits
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter all inputs")
            msg.exec()
            return None


    def close_form(self):
        #clear the inputs
        self.lineEdit_contribution.clear()
        self.lineEdit_goal.clear()
        self.lineEdit_return_rate.clear()

        #go back to page 1
        self.stackedWidget.setCurrentIndex(0)


if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())