# Form implementation generated from reading ui file 'multiform_car_search_filter.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 598)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 70, 671, 391))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.pushButton_main_search = QtWidgets.QPushButton(parent=self.main)
        self.pushButton_main_search.setGeometry(QtCore.QRect(160, 80, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_main_search.setFont(font)
        self.pushButton_main_search.setObjectName("pushButton_main_search")

        self.pushButton_main_search.clicked.connect(self.main_search)

        self.pushButton_main_filter = QtWidgets.QPushButton(parent=self.main)
        self.pushButton_main_filter.setGeometry(QtCore.QRect(400, 80, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_main_filter.setFont(font)
        self.pushButton_main_filter.setObjectName("pushButton_main_filter")

        self.pushButton_main_filter.clicked.connect(self.main_filter)

        self.pushButton_main_exit = QtWidgets.QPushButton(parent=self.main)
        self.pushButton_main_exit.setGeometry(QtCore.QRect(280, 170, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_main_exit.setFont(font)
        self.pushButton_main_exit.setObjectName("pushButton_main_exit")

        self.pushButton_main_exit.clicked.connect(self.exit)

        self.stackedWidget.addWidget(self.main)
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.label_select_model = QtWidgets.QLabel(parent=self.search)
        self.label_select_model.setGeometry(QtCore.QRect(90, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_select_model.setFont(font)
        self.label_select_model.setObjectName("label_select_model")
        self.label_model_price = QtWidgets.QLabel(parent=self.search)
        self.label_model_price.setGeometry(QtCore.QRect(380, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_model_price.setFont(font)
        self.label_model_price.setObjectName("label_model_price")
        self.comboBox = QtWidgets.QComboBox(parent=self.search)
        self.comboBox.setGeometry(QtCore.QRect(90, 90, 191, 41))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(parent=self.search)
        self.pushButton.setGeometry(QtCore.QRect(260, 190, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.close_search)

        self.label_search_model_price = QtWidgets.QLabel(parent=self.search)
        self.label_search_model_price.setGeometry(QtCore.QRect(380, 90, 201, 41))
        self.label_search_model_price.setText("")
        self.label_search_model_price.setObjectName("label_search_model_price")
        self.stackedWidget.addWidget(self.search)
        self.filter = QtWidgets.QWidget()
        self.filter.setObjectName("filter")
        self.label = QtWidgets.QLabel(parent=self.filter)
        self.label.setGeometry(QtCore.QRect(80, 60, 151, 31))
        self.label.setObjectName("label")
        self.lineEdit_filter_price = QtWidgets.QLineEdit(parent=self.filter)
        self.lineEdit_filter_price.setGeometry(QtCore.QRect(80, 100, 161, 41))
        self.lineEdit_filter_price.setObjectName("lineEdit_filter_price")
        self.pushButton_filter_filter = QtWidgets.QPushButton(parent=self.filter)
        self.pushButton_filter_filter.setGeometry(QtCore.QRect(320, 90, 131, 41))
        self.pushButton_filter_filter.setObjectName("pushButton_filter_filter")

        self.pushButton_filter_close = QtWidgets.QPushButton(parent=self.filter)
        self.pushButton_filter_close.setGeometry(QtCore.QRect(500, 90, 131, 41))
        self.pushButton_filter_close.setObjectName("pushButton_filter_close")

        self.pushButton_filter_close.clicked.connect(self.close_filter)

        self.tableWidget = QtWidgets.QTableWidget(parent=self.filter)
        self.tableWidget.setGeometry(QtCore.QRect(90, 160, 501, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.stackedWidget.addWidget(self.filter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.data = {}

        import json

        with open("C:/Users/amryb/Desktop/ABP/NCSU/BUS 442/In class/multiform_car_search_filter.json") as file_handler:
            self.data = json.load(file_handler)
        print("data loaded from file", self.data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_main_search.setText(_translate("MainWindow", "Search"))
        self.pushButton_main_filter.setText(_translate("MainWindow", "Filter"))
        self.pushButton_main_exit.setText(_translate("MainWindow", "Exit"))
        self.label_select_model.setText(_translate("MainWindow", "Select Model"))
        self.label_model_price.setText(_translate("MainWindow", "Model Price"))
        self.pushButton.setText(_translate("MainWindow", "Close"))
        self.label.setText(_translate("MainWindow", "Enter Price"))
        self.pushButton_filter_filter.setText(_translate("MainWindow", "Filter"))
        self.pushButton_filter_close.setText(_translate("MainWindow", "Close"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Model"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Price"))

    def exit(self):
        application.exit()

    #code when user clicks on the "search' button on the main page
    def main_search(self):
        self.stackedWidget.setCurrentIndex(1)   # show the search page to the user
        self.comboBox.addItems(self.data.keys())    #add all cars to the combobox
        self.comboBox.activated.connect(self.display_search) # call function display search when the user makes a selection from the combobox

    def display_search(self):
        user_selection = self.comboBox.currentText() # accept user selection from the combobox
        print("Value from the user", self.data[user_selection])
        self.label_search_model_price.setText(str("$")+self.data[user_selection])

    #close the search page
    def close_search(self):
        self.label_search_model_price.clear() #clearthe display of price
        self.comboBox.setCurrentIndex(0)     # reset combobox to original value
        self.stackedWidget.setCurrentIndex(0)   #sow the main page of the application

    def main_filter(self):
        self.stackedWidget.setCurrentIndex(2)
        self.pushButton_filter_filter.clicked.connect(self.filter_results)

    def filter_results(self):
        if len(self.lineEdit_filter_price.text()) > 0 and self.lineEdit_filter_price.text().isdigit():
            user_input = float(self.lineEdit_filter_price.text())   #acept user input
            self.tableWidget.setRowCount(0)     # set rows in the table to 0
            for model in self.data.keys():      # iterate iver all models in the data
                if user_input >= float(self.data[model]):  # filter models where user input >= model price
                    row = self.tableWidget.rowCount()
                    self.tableWidget.insertRow(row)
                    self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(model)))
                    self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(self.data[model])))

    def close_filter(self):
        self.lineEdit_filter_price.clear()  # clear user input
        self.tableWidget.setRowCount(0)     # clear the table
        self.stackedWidget.setCurrentIndex(0)      #go back to main page of the application


if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())