# Form implementation generated from reading ui file 'NCStateFairApp.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(40, 20, 721, 521))
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.pushButton_dashboard_purchase = QtWidgets.QPushButton(parent=self.dashboard)
        self.pushButton_dashboard_purchase.setGeometry(QtCore.QRect(150, 191, 114, 34))
        self.pushButton_dashboard_purchase.setObjectName("pushButton_dashboard_purchase")

        self.pushButton_dashboard_purchase.clicked.connect(self.purchase)

        self.pushButton_dashboard_display = QtWidgets.QPushButton(parent=self.dashboard)
        self.pushButton_dashboard_display.setGeometry(QtCore.QRect(490, 191, 114, 34))
        self.pushButton_dashboard_display.setObjectName("pushButton_dashboard_display")

        self.pushButton_dashboard_display.clicked.connect(self.display)

        self.label_dashboad_name = QtWidgets.QLabel(parent=self.dashboard)
        self.label_dashboad_name.setGeometry(QtCore.QRect(220, 110, 141, 31))
        self.label_dashboad_name.setObjectName("label_dashboad_name")
        self.lineEdit_dashboard_name = QtWidgets.QLineEdit(parent=self.dashboard)
        self.lineEdit_dashboard_name.setGeometry(QtCore.QRect(280, 109, 191, 31))
        self.lineEdit_dashboard_name.setObjectName("lineEdit_dashboard_name")
        self.pushButton_dashboard_search = QtWidgets.QPushButton(parent=self.dashboard)
        self.pushButton_dashboard_search.setGeometry(QtCore.QRect(320, 191, 114, 34))
        self.pushButton_dashboard_search.setObjectName("pushButton_dashboard_search")

        self.pushButton_dashboard_search.clicked.connect(self.search)

        self.pushButton_dashboard_exit = QtWidgets.QPushButton(parent=self.dashboard)
        self.pushButton_dashboard_exit.setGeometry(QtCore.QRect(320, 291, 114, 34))
        self.pushButton_dashboard_exit.setObjectName("pushButton_dashboard_exit")

        self.pushButton_dashboard_exit.clicked.connect(self.exit)

        self.stackedWidget.addWidget(self.dashboard)
        self.purchase = QtWidgets.QWidget()
        self.purchase.setObjectName("purchase")
        self.label_purchase_id = QtWidgets.QLabel(parent=self.purchase)
        self.label_purchase_id.setGeometry(QtCore.QRect(80, 50, 121, 31))
        self.label_purchase_id.setObjectName("label_purchase_id")
        self.lineEdit_purchase_transaction_id = QtWidgets.QLineEdit(parent=self.purchase)
        self.lineEdit_purchase_transaction_id.setGeometry(QtCore.QRect(180, 40, 191, 41))
        self.lineEdit_purchase_transaction_id.setObjectName("lineEdit_purchase_transaction_id")
        self.comboBox_purchase_ticket_type = QtWidgets.QComboBox(parent=self.purchase)
        self.comboBox_purchase_ticket_type.setGeometry(QtCore.QRect(180, 160, 191, 41))
        self.comboBox_purchase_ticket_type.setObjectName("comboBox_purchase_ticket_type")
        self.label_purchase_ticket_type = QtWidgets.QLabel(parent=self.purchase)
        self.label_purchase_ticket_type.setGeometry(QtCore.QRect(90, 170, 90, 26))
        self.label_purchase_ticket_type.setObjectName("label_purchase_ticket_type")
        self.label_purchase_quantity = QtWidgets.QLabel(parent=self.purchase)
        self.label_purchase_quantity.setGeometry(QtCore.QRect(100, 110, 90, 26))
        self.label_purchase_quantity.setObjectName("label_purchase_quantity")
        self.lineEdit_purchase_quantity = QtWidgets.QLineEdit(parent=self.purchase)
        self.lineEdit_purchase_quantity.setGeometry(QtCore.QRect(180, 100, 191, 41))
        self.lineEdit_purchase_quantity.setObjectName("lineEdit_purchase_quantity")
        self.pushButton_purchase_purchase = QtWidgets.QPushButton(parent=self.purchase)
        self.pushButton_purchase_purchase.setGeometry(QtCore.QRect(180, 340, 114, 34))
        self.pushButton_purchase_purchase.setObjectName("pushButton_purchase_purchase")

        self.pushButton_purchase_purchase.clicked.connect(self.purchase_transaction)

        self.label_purchase_subtotal_display = QtWidgets.QLabel(parent=self.purchase)
        self.label_purchase_subtotal_display.setGeometry(QtCore.QRect(110, 250, 90, 26))
        self.label_purchase_subtotal_display.setText("")
        self.label_purchase_subtotal_display.setObjectName("label_purchase_subtotal_display")
        self.label_purchase_subtotal = QtWidgets.QLabel(parent=self.purchase)
        self.label_purchase_subtotal.setGeometry(QtCore.QRect(40, 250, 90, 26))
        self.label_purchase_subtotal.setObjectName("label_purchase_subtotal")
        self.label_purchase_tax_display = QtWidgets.QLabel(parent=self.purchase)
        self.label_purchase_tax_display.setGeometry(QtCore.QRect(310, 250, 90, 26))
        self.label_purchase_tax_display.setText("")
        self.label_purchase_tax_display.setObjectName("label_purchase_tax_display")
        self.label_purchase_tax = QtWidgets.QLabel(parent=self.purchase)
        self.label_purchase_tax.setGeometry(QtCore.QRect(240, 250, 90, 26))
        self.label_purchase_tax.setObjectName("label_purchase_tax")
        self.label_purchase_total_display = QtWidgets.QLabel(parent=self.purchase)
        self.label_purchase_total_display.setGeometry(QtCore.QRect(500, 250, 90, 26))
        self.label_purchase_total_display.setText("")
        self.label_purchase_total_display.setObjectName("label_purchase_total_display")
        self.label_purchase_total_price = QtWidgets.QLabel(parent=self.purchase)
        self.label_purchase_total_price.setGeometry(QtCore.QRect(430, 250, 90, 26))
        self.label_purchase_total_price.setObjectName("label_purchase_total_price")
        self.pushButton_purchase_close = QtWidgets.QPushButton(parent=self.purchase)
        self.pushButton_purchase_close.setGeometry(QtCore.QRect(370, 340, 114, 34))
        self.pushButton_purchase_close.setObjectName("pushButton_purchase_close")

        self.pushButton_purchase_close.clicked.connect(self.close_purchase)

        self.stackedWidget.addWidget(self.purchase)
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.comboBox_search_unique_ticket_type = QtWidgets.QComboBox(parent=self.search)
        self.comboBox_search_unique_ticket_type.setGeometry(QtCore.QRect(180, 60, 181, 41))
        self.comboBox_search_unique_ticket_type.setObjectName("comboBox_search_unique_ticket_type")
        self.label_search_ticket_type = QtWidgets.QLabel(parent=self.search)
        self.label_search_ticket_type.setGeometry(QtCore.QRect(20, 70, 131, 26))
        self.label_search_ticket_type.setObjectName("label_search_ticket_type")
        self.label_search_avg_price = QtWidgets.QLabel(parent=self.search)
        self.label_search_avg_price.setGeometry(QtCore.QRect(20, 130, 90, 26))
        self.label_search_avg_price.setObjectName("label_search_avg_price")
        self.label_search_avg_price_display = QtWidgets.QLabel(parent=self.search)
        self.label_search_avg_price_display.setGeometry(QtCore.QRect(120, 130, 90, 26))
        self.label_search_avg_price_display.setText("")
        self.label_search_avg_price_display.setObjectName("label_search_avg_price_display")
        self.tableWidget_search_transactions = QtWidgets.QTableWidget(parent=self.search)
        self.tableWidget_search_transactions.setGeometry(QtCore.QRect(225, 160, 620, 271))
        self.tableWidget_search_transactions.setObjectName("tableWidget_search_transactions")
        self.tableWidget_search_transactions.setColumnCount(0)
        self.tableWidget_search_transactions.setRowCount(0)
        self.label_search_transations = QtWidgets.QLabel(parent=self.search)
        self.label_search_transations.setGeometry(QtCore.QRect(225, 130, 90, 26))
        self.label_search_transations.setObjectName("label_search_transations")
        self.pushButton_search_close = QtWidgets.QPushButton(parent=self.search)
        self.pushButton_search_close.setGeometry(QtCore.QRect(300, 470, 114, 34))
        self.pushButton_search_close.setObjectName("pushButton_search_close")

        self.pushButton_search_close.clicked.connect(self.close_search)

        self.stackedWidget.addWidget(self.search)
        self.display = QtWidgets.QWidget()
        self.display.setObjectName("display")
        self.tableWidget_display = QtWidgets.QTableWidget(parent=self.display)
        self.tableWidget_display.setGeometry(QtCore.QRect(50, 40, 621, 361))
        self.tableWidget_display.setObjectName("tableWidget_display")
        self.tableWidget_display.setColumnCount(0)
        self.tableWidget_display.setRowCount(0)
        self.pushButton_display_close = QtWidgets.QPushButton(parent=self.display)
        self.pushButton_display_close.setGeometry(QtCore.QRect(300, 430, 114, 34))
        self.pushButton_display_close.setObjectName("pushButton_display_close")

        self.pushButton_display_close.clicked.connect(self.close_display)

        self.stackedWidget.addWidget(self.display)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 22))
        self.menubar.setObjectName("menubar")
        self.menuNC_State_Fair = QtWidgets.QMenu(parent=self.menubar)
        self.menuNC_State_Fair.setObjectName("menuNC_State_Fair")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuNC_State_Fair.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.ticket_prices = {}
        self.ticket_types = {}


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_dashboard_purchase.setText(_translate("MainWindow", "Purchase"))
        self.pushButton_dashboard_display.setText(_translate("MainWindow", "Display"))
        self.label_dashboad_name.setText(_translate("MainWindow", "Name:"))
        self.pushButton_dashboard_search.setText(_translate("MainWindow", "Search"))
        self.pushButton_dashboard_exit.setText(_translate("MainWindow", "Exit"))
        self.label_purchase_id.setText(_translate("MainWindow", "Transaction Id:"))
        self.label_purchase_ticket_type.setText(_translate("MainWindow", "Ticket Type:"))
        self.label_purchase_quantity.setText(_translate("MainWindow", "Quantity:"))
        self.pushButton_purchase_purchase.setText(_translate("MainWindow", "Purchase"))
        self.label_purchase_subtotal.setText(_translate("MainWindow", "Subtotal:"))
        self.label_purchase_tax.setText(_translate("MainWindow", "Tax(8%):"))
        self.label_purchase_total_price.setText(_translate("MainWindow", "Total Price:"))
        self.pushButton_purchase_close.setText(_translate("MainWindow", "Close"))
        self.label_search_ticket_type.setText(_translate("MainWindow", "Unique Ticket Type"))
        self.label_search_avg_price.setText(_translate("MainWindow", "Average Price:"))
        self.label_search_transations.setText(_translate("MainWindow", "Transactions:"))
        self.pushButton_search_close.setText(_translate("MainWindow", "Close"))
        self.pushButton_display_close.setText(_translate("MainWindow", "Close"))
        self.menuNC_State_Fair.setTitle(_translate("MainWindow", "NC State Fair"))

    def exit(self):
        application.exit()


    def establish_connection(self):
        try:
            self.connection = pymysql.connect(
                host="localhost",
                database="finalprojectdb",
                user="bus442",
                password="bus442")

        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not close connection to the database" + str(e))
            msg.exec()

    def close_connection(self):
       try:
           self.connection.close()
       except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not close conection to the database" + str(e))
            msg.exec()

    def read_data_from_database(self):
        try:

            print("in the function read_data_from_database")

            # establish connection to the database
            self.establish_connection()

            # define a cursor --> allows us to iterate over the result
            cursor = self.connection.cursor()

            cursor.execute("select * from fair_ticket_sales;")
            print("cursor content", cursor)

            resultset = cursor.fetchall()  # gets all rows from the SELECT * execution

            print("result set output", resultset)

            self.close_connection()

            return cursor

        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not close connection to the database" + str(e))
            msg.exec()


    # dashboard window:
    def validate_name(self):
        name = self.lineEdit_dashboard_name.text()
        if len(name) > 0:
            return True
        else:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter a name")
            msg.exec()




    # purchase window:
    def purchase(self):

        print("in purchase method")
        if not self.validate_name():
            return

        self.stackedWidget.setCurrentIndex(1)  # show the search page to the user

        with open("C:/Users/amryb/Desktop/ABP/NCSU/BUS 442/In class/price_data.txt") as file_handler:
            for data_line in file_handler:
                # print(data_line)
                data = data_line.rstrip("\n")
                data = data.split(",")
                print(data)

                self.ticket_prices[data[0]] = (data[1])

            self.comboBox_purchase_ticket_type.addItems(self.ticket_prices.keys())  # add all cars to the combobox

            self.comboBox_purchase_ticket_type.activated.connect(self.display_purchase)  # call function display purchase when the user makes a selection from the combobox

    def display_purchase(self):
        print("in display_purchase method")

        ticket_type = self.comboBox_purchase_ticket_type.currentText()  # accept user selection from the combobox
        quantity = 0
        print("User selection:", ticket_type)
        try:
            quantity = int(self.lineEdit_purchase_quantity.text())
        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Invalid input, \nPlease enter a number")
            msg.exec()

        # subtotal (price * quantity), tax at 8%, and the total price on the same page.
        subtotal = quantity * float(self.ticket_prices[ticket_type])
        tax = subtotal * 0.08
        total = subtotal + tax

        print("subtotal", subtotal)
        print("tax", tax)
        print("total", total)

        self.label_purchase_subtotal_display.setText(str("$")+str(subtotal))
        self.label_purchase_tax_display.setText(str("$")+str(tax))
        self.label_purchase_total_display.setText(str(total))

    #Add a “Purchase” button
    def purchase_transaction(self):
        print("in purchase_transaction method")

        # user input validation

        if len(self.lineEdit_purchase_quantity.text()) > 0 and self.comboBox_purchase_ticket_type.currentText() != "":
            print("User input acceptable")

            self.establish_connection()  # establish connection to the databse
            self.cursor = self.connection.cursor()  # create cursor
            self.cursor.execute("select * from fair_ticket_sales;")
            resultset = self.cursor.fetchall()

            check_transaction_id = 0

            for record in resultset:
                print(record)
                if record[0] == int(self.lineEdit_purchase_transaction_id.text()):
                    check_student_id = 1
                    print("Check of transaction id exists --> yes")
                    msg = QtWidgets.QMessageBox()
                    msg.setText("Transaction id already exists")
                    msg.exec()
                    return


            # insert transaction (transactionid, customername, tickettype,
            # quantity, total) to the fair_ticket_sales table on success
            print('trying to insert record')

            ''' -- 2. In the new schema, create a fair_ticket_sales table with columns 
                -- transactionid (int primary key), customername (varchar), 
                -- tickettype (varchar), quantity (int), total (int)
            '''

            query = "INSERT INTO fair_ticket_sales VALUES (%s, %s, %s, %s, %s)"

            arguments = (int(self.lineEdit_purchase_transaction_id.text()),
                         self.lineEdit_dashboard_name.text(), self.comboBox_purchase_ticket_type.currentText(),
                         int(self.lineEdit_purchase_quantity.text()),
                         float(self.label_purchase_total_display.text()))

            print(query, arguments)

            self.cursor.execute(query, arguments)  # execute the query
            self.connection.commit()

            self.close_connection()
            msg = QtWidgets.QMessageBox()
            #Show message to the user (“Success” or “Error”
            msg.setText("SUCCESS: Transaction added successfully")
            msg.exec()


        else:
            msg = QtWidgets.QMessageBox()
            #Show message to the user (“Success” or “Error”
            msg.setText("ERROR: Please enter valid information for all input")
            msg.exec()

    def close_purchase(self):

        self.stackedWidget.setCurrentIndex(0)  # show the main page of the application







    # search window:
    def search(self):
        with open("C:/Users/amryb/Desktop/ABP/NCSU/BUS 442/In class/price_data.txt") as file_handler:
            for data_line in file_handler:
                # print(data_line)
                data = data_line.rstrip("\n")
                data = data.split(",")
                print(data)

                ticket_type = data[0]
                price = float(data[1])

                self.ticket_prices[ticket_type] = price

        self.comboBox_search_unique_ticket_type.addItems(self.ticket_prices.keys())  # add all cars to the combobox
        self.stackedWidget.setCurrentIndex(2)

        self.comboBox_search_unique_ticket_type.activated.connect(self.display_search)  # call function display search when the user makes a selection from the combobox

    def display_search(self):
        print("in display_search method")

        self.establish_connection()  # establish connection to the databse
        self.cursor = self.connection.cursor()  # create cursor
        self.cursor.execute("select * from fair_ticket_sales;")
        resultset = self.cursor.fetchall()

        try:
            print("Display transaction according to ticket type")

            # read from data
            cursor= self.read_data_from_database()
            columns = []
            for col in cursor.description:
                columns.append(col[0])
            self.tableWidget_search_transactions.setColumnCount(len(columns))  # add the number of columns to the table as many as the length
            self.tableWidget_search_transactions.setHorizontalHeaderLabels(columns)

            user_input = self.comboBox_search_unique_ticket_type.currentText()  # acept user input
            print("User selection:", user_input)
            self.tableWidget_search_transactions.setRowCount(0)  # set rows in the table to 0

            prices = [] #collect prices for calculating average, define prices to call later

            for transaction in resultset:
                print("row in resultset", transaction)

                if user_input == transaction[2]:
                    print("in if transaction == user input")
                    row = self.tableWidget_search_transactions.rowCount()
                    self.tableWidget_search_transactions.insertRow(row)

                    for i in range(len(transaction)):   # i --> for every column in database    #- Loops through every column in the SQL row.
                        value = transaction[i]  # each value in column i
                        self.tableWidget_search_transactions.setItem(row, i, QtWidgets.QTableWidgetItem(str(value)))

                        prices.append(float(transaction[4]))    #collect prices from sql
                        print("prices", prices)
                        sum_ticket_price = sum(prices)
                        print("sum of ticket prices",sum_ticket_price)
                        average_price = sum_ticket_price / len(prices)
                        print("avg price", average_price)
                        # Display the average price using a read only lineEdit widget.
                        self.label_search_avg_price_display.setText(str(average_price))


        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not display to table" + str(e))
            msg.exec()

    def close_search(self):
        self.stackedWidget.setCurrentIndex(0)  # show the main page of the application




    #display window
    #Retrieve all transactions from the fair_ticket_sales table and display using a tablewidget.
    def display(self):
        print("in display method")

        self.stackedWidget.setCurrentIndex(3)

        self.establish_connection()  # establish connection to the databse
        self.cursor = self.connection.cursor()  # create cursor
        self.cursor.execute("select * from fair_ticket_sales;")
        resultset = self.cursor.fetchall()

        try:
            print("in the function display")

            cursor = self.read_data_from_database()

            columns = []
            for col in cursor.description:
                columns.append(col[0])
                print(col, columns)

            self.tableWidget_display.setColumnCount(len(columns))  # add the number of columns to the table as many as the length

            self.tableWidget_display.setHorizontalHeaderLabels(columns)

            self.tableWidget_display.setRowCount(0)  # set the number of rowd to be 0
            print("table is set")
            for record in resultset:
                print("row in resultset", record)
                rows = self.tableWidget_display.rowCount()
                self.tableWidget_display.insertRow(rows)
                self.tableWidget_display.setItem(rows, 0, QtWidgets.QTableWidgetItem(str(record[0])))
                self.tableWidget_display.setItem(rows, 1, QtWidgets.QTableWidgetItem(str(record[1])))
                self.tableWidget_display.setItem(rows, 2, QtWidgets.QTableWidgetItem(str(record[2])))
                self.tableWidget_display.setItem(rows, 3, QtWidgets.QTableWidgetItem(str(record[3])))
                self.tableWidget_display.setItem(rows, 4, QtWidgets.QTableWidgetItem(str(record[4])))


        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not display to table" + str(e))
            msg.exec()

    def close_display(self):
        self.stackedWidget.setCurrentIndex(0)  # show the main page of the application

if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())