# Form implementation generated from reading ui file 'purchase_tickets.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QComboBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 60, 701, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.purchase = QtWidgets.QWidget()
        self.purchase.setObjectName("purchase")
        self.label_name = QtWidgets.QLabel(parent=self.purchase)
        self.label_name.setGeometry(QtCore.QRect(50, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.purchase)
        self.lineEdit_name.setGeometry(QtCore.QRect(120, 40, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_age = QtWidgets.QLabel(parent=self.purchase)
        self.label_age.setGeometry(QtCore.QRect(50, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_age.setFont(font)
        self.label_age.setObjectName("label_age")
        self.label_ticket_type = QtWidgets.QLabel(parent=self.purchase)
        self.label_ticket_type.setGeometry(QtCore.QRect(50, 130, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_ticket_type.setFont(font)
        self.label_ticket_type.setWordWrap(True)
        self.label_ticket_type.setObjectName("label_ticket_type")
        self.lineEdit_age = QtWidgets.QLineEdit(parent=self.purchase)
        self.lineEdit_age.setGeometry(QtCore.QRect(120, 90, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_age.setFont(font)
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.comboBox = QtWidgets.QComboBox(parent=self.purchase)
        self.comboBox.setGeometry(QtCore.QRect(120, 140, 161, 41))
        self.comboBox.setObjectName("comboBox")
        self.label_cost = QtWidgets.QLabel(parent=self.purchase)
        self.label_cost.setGeometry(QtCore.QRect(50, 200, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_cost.setFont(font)
        self.label_cost.setObjectName("label_cost")
        self.label_cost_display = QtWidgets.QLabel(parent=self.purchase)
        self.label_cost_display.setGeometry(QtCore.QRect(120, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_cost_display.setFont(font)
        self.label_cost_display.setText("")
        self.label_cost_display.setObjectName("label_cost_display")
        self.pushButton_show_cost = QtWidgets.QPushButton(parent=self.purchase)
        self.pushButton_show_cost.setGeometry(QtCore.QRect(80, 260, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_show_cost.setFont(font)
        self.pushButton_show_cost.setObjectName("pushButton_show_cost")

        self.pushButton_show_cost.clicked.connect(self.show_ticket_cost)

        self.pushButton_complete_purchase = QtWidgets.QPushButton(parent=self.purchase)
        self.pushButton_complete_purchase.setGeometry(QtCore.QRect(220, 260, 201, 41))

        self.pushButton_complete_purchase.clicked.connect(self.complete_purchase)

        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_complete_purchase.setFont(font)
        self.pushButton_complete_purchase.setObjectName("pushButton_complete_purchase")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.purchase)
        self.pushButton_exit.setGeometry(QtCore.QRect(440, 260, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.pushButton_exit.clicked.connect(self.exit)

        self.label_number_tickets = QtWidgets.QLabel(parent=self.purchase)
        self.label_number_tickets.setGeometry(QtCore.QRect(460, 40, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_number_tickets.setFont(font)
        self.label_number_tickets.setObjectName("label_number_tickets")
        self.radioButton_one = QtWidgets.QRadioButton(parent=self.purchase)
        self.radioButton_one.setGeometry(QtCore.QRect(460, 90, 83, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_one.setFont(font)
        self.radioButton_one.setObjectName("radioButton_one")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_one)
        self.radioButton_two = QtWidgets.QRadioButton(parent=self.purchase)
        self.radioButton_two.setGeometry(QtCore.QRect(510, 90, 83, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_two.setFont(font)
        self.radioButton_two.setObjectName("radioButton_two")
        self.buttonGroup.addButton(self.radioButton_two)
        self.radioButton_three = QtWidgets.QRadioButton(parent=self.purchase)
        self.radioButton_three.setGeometry(QtCore.QRect(560, 90, 83, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_three.setFont(font)
        self.radioButton_three.setObjectName("radioButton_three")
        self.buttonGroup.addButton(self.radioButton_three)
        self.tabWidget.addTab(self.purchase, "")
        self.tab_purchase_completed = QtWidgets.QWidget()
        self.tab_purchase_completed.setObjectName("tab_purchase_completed")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tab_purchase_completed)
        self.tableWidget.setGeometry(QtCore.QRect(30, 40, 571, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_purchase_completed, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.comboBox.addItems(["Courtside", "Midlevel", "Toplevel"])

        self.ticket_prices = {}

        #
        self.all_transactions = {}

        self.tabWidget.tabBarClicked.connect(self.display_purchases)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Name"))
        self.label_age.setText(_translate("MainWindow", "Age"))
        self.label_ticket_type.setText(_translate("MainWindow", "Ticket Type"))
        self.label_cost.setText(_translate("MainWindow", "Cost"))
        self.pushButton_show_cost.setText(_translate("MainWindow", "Show Cost"))
        self.pushButton_complete_purchase.setText(_translate("MainWindow", "Complete Purchase"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        self.label_number_tickets.setText(_translate("MainWindow", "Number of Tickets"))
        self.radioButton_one.setText(_translate("MainWindow", "1"))
        self.radioButton_two.setText(_translate("MainWindow", "2"))
        self.radioButton_three.setText(_translate("MainWindow", "3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.purchase), _translate("MainWindow", "Purchase Ticket"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Age"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ticket Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Number of Tickets"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cost"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_purchase_completed), _translate("MainWindow", "Purchases"))

    # Exit Functionality: close the application
    def exit(self):
        application.exit()

    def show_ticket_cost(self):
        print("In show_ticket_cost function")

        #code for no name

        if self.buttonGroup.checkedButton() == None:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please select the number of tickets")
            msg.exec()
            return None

        with open("C:/Users/amryb/Desktop/ABP/NCSU/BUS 442/In class/Tickets.txt") as file_handler:
            for data_line in file_handler:
                #print(data_line)
                data = data_line.rstrip("\n")
                data = data.split(",")
                print(data)
                self.ticket_prices[data[0]] = float(data[1])
        print("ticket prices read from the file", self.ticket_prices)

        ticket_type = self.comboBox.currentText()
        print("ticket type selected by user:", ticket_type)

        number_of_tickets = int(self.buttonGroup.checkedButton().text())
        print("number of tickets selected by user:", number_of_tickets)

        ticket_price = number_of_tickets * self.ticket_prices[ticket_type]
        print("ticket price:", ticket_price)
        self.label_cost_display.setText(str(ticket_price))

        return ticket_price     # return the computed cost of ticket. This is need for when we call this function in another function.

    def complete_purchase(self):
        print("In complete_purchase function")

        #step 1: find the cost of the transaction -> already on the show_ticket_cost function
        transaction_cost = self.show_ticket_cost()      #calling the function
        print("transaction_cost calculated:", transaction_cost)

        #step 2: read data
        import json
        with open("C:/Users/amryb/Desktop/ABP/NCSU/BUS 442/In class/Tickets_purchased.json") as file_handler:
            self.all_transactions = json.load(file_handler)
        print("transactions so far:", self.all_transactions)

        #step 3 -->  find the record number to be added
        if len(self.all_transactions) > 0:
            get_keys = int(max(self.all_transactions.keys()))
            get_keys = get_keys + 1
        else:
            get_keys = 1
        print("new key to be added:", get_keys)

        self.all_transactions[get_keys] = {}
        self.all_transactions[get_keys]["name"] = self.lineEdit_name.text()
        self.all_transactions[get_keys]["age"] = self.lineEdit_age.text()
        self.all_transactions[get_keys]["number_of_tickets"] = int(self.buttonGroup.checkedButton().text())
        self.all_transactions[get_keys]["ticket_type"] = self.comboBox.currentText()
        self.all_transactions[get_keys]["cost"] = transaction_cost

        self.display_purchases()

        with open("C:/Users/amryb/Desktop/ABP/NCSU/BUS 442/In class/Tickets_purchased.json", "w") as file_handler:
            json.dump(self.all_transactions, file_handler)


        msg = QtWidgets.QMessageBox()
        msg.setText("Transacation complete and recorded")
        msg.exec()

        #set all inouts for next transaction
        self.lineEdit_name.clear()
        self.lineEdit_age.clear()
        self.buttonGroup.setExclusive(False)
        self.radioButton_one.setChecked(False)
        self.radioButton_two.setChecked(False)
        self.radioButton_three.setChecked(False)
        self.buttonGroup.setExclusive(False)
        self.label_cost_display.clear()

    def display_purchases(self):
        #read the json file
        print("in display_purchases")
        self.tableWidget.setRowCount(0)
        for name, purchase in self.all_transactions.items():
            print(name, purchase)
            print(purchase['name'], purchase['age'], purchase['number_of_tickets'], purchase['ticket_type'], purchase['cost'])

            row = self.tableWidget.rowCount()
            self.tableWidget.insertRow(row)

            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(purchase['name']))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(purchase['age']))
            self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str(purchase['number_of_tickets'])))
            self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(purchase['ticket_type']))
            self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(str(purchase['cost'])))



if __name__ == '__main__':#
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())