# Form implementation generated from reading ui file 'retrieve_database.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 50, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.read_data_from_database)

        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 140, 691, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Import Data"))

    def establish_connection(self):
        try:
            self.connection = pymysql.connect(
                host="localhost",
                database="student",
                user="bus442",
                password="bus442")
            msg = QtWidgets.QMessageBox()
            msg.setText("Connection established")
            msg.exec()
        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not close conection to the database" + str(e))
            msg.exec()

    def close_connection(self):
       try:
           self.connection.close()
       except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not close conection to the database" + str(e))
            msg.exec()


    def read_data_from_database(self):
        try:

            print("in the function read_data_from_database")

            # establish connection to the database
            self.establish_connection()

            # define a cursor --> allows us to iterate over the result
            cursor = self.connection.cursor()

            cursor.execute("select * from project4db.student_table;")
            print("cursor content", cursor)

            resultset = cursor.fetchall()   # gets all rows from the SELECT * execution
            print("result set output", resultset)
            print("type of resultset", type(resultset))

            columns = []
            for col in cursor.description:
                columns.append(col[0])
                print(col, columns)

            columns.append("Eligibility")   # add the column to the data table
            print("Number of columns", len(columns), columns)


            self.tableWidget.setColumnCount(len(columns)) # add the number of columns to the table as many as the length

            self.tableWidget.setHorizontalHeaderLabels(columns)

            self.tableWidget.setRowCount(0)  #set the number of rowd to be 0
            print("table is set")
            for record in resultset:
                print("row in resultset", record)
                rows = self.tableWidget.rowCount()
                self.tableWidget.insertRow(rows)
                self.tableWidget.setItem(rows, 0, QtWidgets.QTableWidgetItem(str(record[0])))
                self.tableWidget.setItem(rows, 1, QtWidgets.QTableWidgetItem(str(record[1])))
                self.tableWidget.setItem(rows, 2, QtWidgets.QTableWidgetItem(str(record[2])))

                if record[2] >= 21:
                    self.tableWidget.setItem(rows, 3, QtWidgets.QTableWidgetItem("Yes"))
                else:
                    self.tableWidget.setItem(rows, 3, QtWidgets.QTableWidgetItem("No"))




            self.close_connection()

        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not close conection to the database" + str(e))
            msg.exec()



if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())