# Form implementation generated from reading ui file 'student_grade.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_score = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_score.setGeometry(QtCore.QRect(220, 120, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_score.setFont(font)
        self.label_score.setObjectName("label_score")
        self.lineEdit_score = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_score.setGeometry(QtCore.QRect(362, 110, 161, 51))
        self.lineEdit_score.setObjectName("lineEdit_score")
        self.pushButton_generate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_generate.setGeometry(QtCore.QRect(130, 220, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_generate.setFont(font)
        self.pushButton_generate.setObjectName("pushButton_generate")

        self.pushButton_generate.clicked.connect(self.calculate_grade_gpa)

        self.pushButton_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(400, 220, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")

        # code for clear button
        self.pushButton_clear.clicked.connect(self.clear)
        
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(550, 220, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        
        # code for exit button
        self.pushButton_exit.clicked.connect(self.exit)
        
        self.label_grade = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_grade.setGeometry(QtCore.QRect(270, 370, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_grade.setFont(font)
        self.label_grade.setObjectName("label_grade")
        self.label_gpa = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_gpa.setGeometry(QtCore.QRect(270, 430, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_gpa.setFont(font)
        self.label_gpa.setObjectName("label_gpa")
        self.label_grade_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_grade_display.setGeometry(QtCore.QRect(376, 370, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_grade_display.setFont(font)
        self.label_grade_display.setText("")
        self.label_grade_display.setObjectName("label_grade_display")
        self.label_gpa_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_gpa_display.setGeometry(QtCore.QRect(380, 430, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_gpa_display.setFont(font)
        self.label_gpa_display.setText("")
        self.label_gpa_display.setObjectName("label_gpa_display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_score.setText(_translate("MainWindow", "Course score: "))
        self.pushButton_generate.setText(_translate("MainWindow", "Generate Grade and GPA"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear "))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        self.label_grade.setText(_translate("MainWindow", "Grade:"))
        self.label_gpa.setText(_translate("MainWindow", "GPA:"))



    def clear(self):
        self.lineEdit_score.clear()
        self.label_grade_display.clear()
        self.label_gpa_display.clear()
       
    def exit(self):
        application.exit()

    def calculate_grade_gpa(self):

        score = int(self.lineEdit_score.text())
        print("Course score provided by the user:", score)
        # step 1 accept user input
        score = int(self.lineEdit_score.text())
        print("Your score is", score)
        # step 2: given score identify the appropraite letter grade
        if score >= 90:
            print("score greater than 90")  # print this to understnad the code
            self.label_grade_display.setText("A")  # label to A so that user can see the outcome
            self.label_gpa_display.setText("4")  # change GPS label for the user
        elif score >= 80:
            print("score greater than 80")
            self.label_grade_display.setText("B")  # label to A so that user can see the outcome
            self.label_gpa_display.setText("3")
        elif score >= 70:
            print("score greater than 70")
            self.label_grade_display.setText("C")  # label to A so that user can see the outcome
            self.label_gpa_display.setText("2")
        elif score >= 60:
            print("score greater than 60")
            self.label_grade_display.setText("D")  # label to A so that user can see the outcome
            self.label_gpa_display.setText("1")
        else:
            print("score less than 60")
            self.label_grade_display.setText("F")
            self.label_gpa_display.setText("0")
            
if __name__ == '__main__':
    import sys
    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())