# Form implementation generated from reading ui file 'Attendance.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(170, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(320, 70, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_score = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_score.setGeometry(QtCore.QRect(170, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_score.setFont(font)
        self.label_score.setObjectName("label_score")
        self.lineEdit_score = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_score.setGeometry(QtCore.QRect(320, 130, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_score.setFont(font)
        self.lineEdit_score.setObjectName("lineEdit_score")
        self.label_attendance = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_attendance.setGeometry(QtCore.QRect(170, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_attendance.setFont(font)
        self.label_attendance.setObjectName("label_attendance")
        self.lineEdit_attendance = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_attendance.setGeometry(QtCore.QRect(320, 190, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_attendance.setFont(font)
        self.lineEdit_attendance.setObjectName("lineEdit_attendance")
        self.pushButton_performance = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_performance.setGeometry(QtCore.QRect(190, 260, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_performance.setFont(font)
        self.pushButton_performance.setObjectName("pushButton_performance")

        self.pushButton_performance.clicked.connect(self.calculate_performance)

        self.label_grade = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_grade.setGeometry(QtCore.QRect(50, 350, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_grade.setFont(font)
        self.label_grade.setObjectName("label_grade")
        self.label_grade_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_grade_display.setGeometry(QtCore.QRect(140, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_grade_display.setFont(font)
        self.label_grade_display.setText("")
        self.label_grade_display.setObjectName("label_grade_display")
        self.label_deans_list_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_deans_list_display.setGeometry(QtCore.QRect(370, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_deans_list_display.setFont(font)
        self.label_deans_list_display.setText("")
        self.label_deans_list_display.setObjectName("label_deans_list_display")
        self.label_deans_list = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_deans_list.setGeometry(QtCore.QRect(270, 350, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_deans_list.setFont(font)
        self.label_deans_list.setObjectName("label_deans_list")
        self.label_passfail_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_passfail_display.setGeometry(QtCore.QRect(610, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_passfail_display.setFont(font)
        self.label_passfail_display.setText("")
        self.label_passfail_display.setObjectName("label_passfail_display")
        self.label_passfail = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_passfail.setGeometry(QtCore.QRect(510, 350, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_passfail.setFont(font)
        self.label_passfail.setObjectName("label_passfail")
        self.pushButton_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(170, 460, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        # code for clear button
        self.pushButton_clear.clicked.connect(self.clear)

        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(420, 460, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        # code for exit button
        self.pushButton_exit.clicked.connect(self.exit)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Name"))
        self.label_score.setText(_translate("MainWindow", "Score"))
        self.label_attendance.setText(_translate("MainWindow", "Attendance"))
        self.pushButton_performance.setText(_translate("MainWindow", "Show Student performance"))
        self.label_grade.setText(_translate("MainWindow", "Grade"))
        self.label_deans_list.setText(_translate("MainWindow", "Dean\'s List"))
        self.label_passfail.setText(_translate("MainWindow", "Pass/Fail"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))

    def exit(self):
        application.exit()


    def clear(self):
        # clear input
        self.lineEdit_name.clear()
        self.lineEdit_score.clear()
        self.lineEdit_attendance.clear()

        # clear application output
        self.label_grade_display.clear()
        self.label_deans_list_display.clear()
        self.label_passfail_display.clear()

    def calculate_performance(self):
        name = self.lineEdit_name.text()
        if len(name) == 0 or not name.isalpha(): #
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter your name")
            msg.exec()

        score = self.lineEdit_score.text()
        if len(score) == 0 or int(score) < 0 or int(score) > 100:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter valid score")
            msg.exec()


        attendance = self.lineEdit_attendance.text()
        if len(attendance) == 0 or int(attendance) < 0 or int(attendance) > 100:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter valid attendance")
            msg.exec()

        score = int(score)
        attendance = int(attendance)
        if score >= 90:
            if attendance >= 90:
                print("Student grade is A, and YES for Dean's list")
                self.label_grade_display.setText("A")
                self.label_deans_list_display.setText("Yes")
                self.label_passfail_display.setText("Pass")
            else:
                print("Student grade is A, and NO for Dean's list")
                self.label_grade_display.setText("A")
                self.label_deans_list_display.setText("No")
                self.label_passfail_display.setText("Pass")
        elif score >= 80:
            print("Student grade is B, and NO for Dean's list")
            self.label_grade_display.setText("B")
            self.label_deans_list_display.setText("No")
            self.label_passfail_display.setText("Pass")
        elif score >= 70:
            print("Student grade is C, and NO for Dean's list")
            self.label_grade_display.setText("C")
            self.label_deans_list_display.setText("No")
            self.label_passfail_display.setText("Pass")
        else:
            print("Student grade is D, and NO for Dean's list")
            self.label_grade_display.setText("D")
            self.label_deans_list_display.setText("No")
            self.label_passfail_display.setText("Fail")

if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())