# Form implementation generated from reading ui file 'StudentApp.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 631)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 10, 961, 571))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_student_info = QtWidgets.QWidget()
        self.tab_student_info.setObjectName("tab_student_info")
        self.tableWidget_data = QtWidgets.QTableWidget(parent=self.tab_student_info)
        self.tableWidget_data.setGeometry(QtCore.QRect(370, 30, 561, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tableWidget_data.setFont(font)
        self.tableWidget_data.setObjectName("tableWidget_data")
        self.tableWidget_data.setColumnCount(0)
        self.tableWidget_data.setRowCount(0)
        self.label_id = QtWidgets.QLabel(parent=self.tab_student_info)
        self.label_id.setGeometry(QtCore.QRect(30, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.pushButton_insert = QtWidgets.QPushButton(parent=self.tab_student_info)
        self.pushButton_insert.setGeometry(QtCore.QRect(80, 420, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_insert.setFont(font)
        self.pushButton_insert.setObjectName("pushButton_insert")

        self.pushButton_insert.clicked.connect(self.insert_data)

        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.tab_student_info)
        self.lineEdit_name.setGeometry(QtCore.QRect(150, 110, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.pushButton_display = QtWidgets.QPushButton(parent=self.tab_student_info)
        self.pushButton_display.setGeometry(QtCore.QRect(550, 420, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_display.setFont(font)
        self.pushButton_display.setObjectName("pushButton_display")

        self.pushButton_display.clicked.connect(self.display_data)

        self.lineEdit_score = QtWidgets.QLineEdit(parent=self.tab_student_info)
        self.lineEdit_score.setGeometry(QtCore.QRect(150, 160, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_score.setFont(font)
        self.lineEdit_score.setObjectName("lineEdit_score")
        self.lineEdit_id = QtWidgets.QLineEdit(parent=self.tab_student_info)
        self.lineEdit_id.setGeometry(QtCore.QRect(150, 50, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_name = QtWidgets.QLabel(parent=self.tab_student_info)
        self.label_name.setGeometry(QtCore.QRect(30, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label_score = QtWidgets.QLabel(parent=self.tab_student_info)
        self.label_score.setGeometry(QtCore.QRect(30, 160, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_score.setFont(font)
        self.label_score.setObjectName("label_score")
        self.tabWidget.addTab(self.tab_student_info, "")
        self.tab_student_grade = QtWidgets.QWidget()
        self.tab_student_grade.setObjectName("tab_student_grade")
        self.tableWidget_grade = QtWidgets.QTableWidget(parent=self.tab_student_grade)
        self.tableWidget_grade.setGeometry(QtCore.QRect(80, 50, 771, 371))
        self.tableWidget_grade.setObjectName("tableWidget_grade")
        self.tableWidget_grade.setColumnCount(0)
        self.tableWidget_grade.setRowCount(0)
        self.pushButton_export = QtWidgets.QPushButton(parent=self.tab_student_grade)
        self.pushButton_export.setGeometry(QtCore.QRect(380, 450, 191, 51))
        self.pushButton_export.setObjectName("pushButton_export")

        self.pushButton_export.clicked.connect(self.export_data)

        self.tabWidget.addTab(self.tab_student_grade, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1039, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)\

        self.tabWidget.tabBarClicked.connect(self.tab_selected)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_id.setText(_translate("MainWindow", "Student Id:"))
        self.pushButton_insert.setText(_translate("MainWindow", "Insert Data"))
        self.pushButton_display.setText(_translate("MainWindow", "Display Data"))
        self.label_name.setText(_translate("MainWindow", "Name:"))
        self.label_score.setText(_translate("MainWindow", "Score:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_student_info), _translate("MainWindow", "Student Info"))
        self.pushButton_export.setText(_translate("MainWindow", "Export Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_student_grade), _translate("MainWindow", "Student Grade"))

    # a function so that student grade is dispalyed in the table widget when clicked on the tab student grade
    def tab_selected(self, index):
        if self.tabWidget.tabText(index) == "Student Grade":
            self.display_grade()

    # step 1 : establish connect to database
    def establish_connection(self):
        try:
            self.connection = pymysql.connect(
                host="localhost",
                #schema name : project4db
                database="project4db",
                user="bus442",
                password="bus442")

        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not close conection to the database" + str(e))
            msg.exec()

    #step 2: close database connection
    def close_connection(self):
       try:
           self.connection.close()
       except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not close conection to the database" + str(e))
            msg.exec()

    # read data in database
    def read_data_from_database(self):
        # establish connection to the database
        self.establish_connection()

        # define a cursor --> allows us to iterate over the result
        cursor = self.connection.cursor()
        cursor.execute("SELECT * FROM student_table;")
        resultset = cursor.fetchall()  # gets all rows from the SELECT * execution
        print("result set output", resultset)

        return cursor, resultset


    #write code for display button  -- display function
    # Button click for Display Data in the Student Info tab: display all rows
    # of data from the database table to the TableWidget
    def display_data(self):
        try:
           print("in the function data display")

           cursor, resultset = self.read_data_from_database()
           columns = []
           for col in cursor.description:
                columns.append(col[0])
                print(col, columns)

           self.tableWidget_data.setColumnCount(len(columns))  # add the number of columns to the table as many as the length

           self.tableWidget_data.setHorizontalHeaderLabels(columns)

           self.tableWidget_data.setRowCount(0)  # set the number of rowd to be 0
           print("table is set")
           for record in resultset:
               print("row in resultset", record)
               rows = self.tableWidget_data.rowCount()
               self.tableWidget_data.insertRow(rows)
               self.tableWidget_data.setItem(rows, 0, QtWidgets.QTableWidgetItem(str(record[0])))
               self.tableWidget_data.setItem(rows, 1, QtWidgets.QTableWidgetItem(str(record[1])))
               self.tableWidget_data.setItem(rows, 2, QtWidgets.QTableWidgetItem(str(record[2])))


           self.close_connection()

        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not display to table" + str(e))
            msg.exec()

    # Button click for Insert Data button: Accept the student id, name, and
    # score and insert data in the table. Display a message in MessageBox
    # to indicate successful addition of data. Display error, if any.
    def insert_data(self):

        print("in the function insert data")

        # user input validation
        if len(self.lineEdit_id.text()) > 0 and len(self.lineEdit_name.text()) > 0 and len(
                self.lineEdit_score.text()) > 0:
            print("Uer input acceptable")

            if self.lineEdit_id.text().isdigit() and self.lineEdit_score.text().isdigit():
                print("User's input verified")

                self.establish_connection()  # establish connection to the databse
                self.cursor = self.connection.cursor()  # create cursor
                self.cursor.execute("SELECT * FROM project4db.student_table;")
                resultset = self.cursor.fetchall()

                check_student_id = 0

                for record in resultset:
                    print(record)
                    if record[0] == int(self.lineEdit_id.text()):
                        check_student_id = 1
                        print("Check of student id exists --> yes")

                # insert new record in table
                if check_student_id == 0:
                    print('trying to insert record')
                    query = "INSERT INTO project4db.student_table VALUES (%s, %s, %s)"

                    arguments = (int(self.lineEdit_id.text()),
                                 self.lineEdit_name.text(),
                                 int(self.lineEdit_score.text()))
                    print(query, arguments)

                    self.cursor.execute(query, arguments)  # eecute the query
                    self.connection.commit()

                    msg = QtWidgets.QMessageBox()
                    msg.setText("Record added successfully")
                    msg.exec()
                else:
                    msg = QtWidgets.QMessageBox()
                    msg.setText("Student id already exists")
                    msg.exec()

            else:
                msg = QtWidgets.QMessageBox()
                msg.setText("Please ensure numeric inputs for ID and score")
                msg.exec()



        else:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter valid information for all input")
            msg.exec()

    def display_grade(self):
        # On click of the Student Grade tab: Display student id, name, score,
        # and grade in TableWidget. Iterate over the data. For each data row,

        try:
            print("in the function grade_display")

            #read from data
            cursor, resultset = self.read_data_from_database()
            columns = []
            for col in cursor.description:
                columns.append(col[0])
                print(col, columns)

            columns.append("Grade")  # add the column to the data table
            print("Number of columns", len(columns), columns)

            self.tableWidget_grade.setColumnCount(len(columns))  # add the number of columns to the table as many as the length

            self.tableWidget_grade.setHorizontalHeaderLabels(columns)

            self.tableWidget_grade.setRowCount(0)  # set the number of rowd to be 0
            print("table is set")
            for record in resultset:
                print("row in resultset", record)
                rows = self.tableWidget_grade.rowCount()
                self.tableWidget_grade.insertRow(rows)
                self.tableWidget_grade.setItem(rows, 0, QtWidgets.QTableWidgetItem(str(record[0])))
                self.tableWidget_grade.setItem(rows, 1, QtWidgets.QTableWidgetItem(str(record[1])))
                self.tableWidget_grade.setItem(rows, 2, QtWidgets.QTableWidgetItem(str(record[2])))

                # grade is F if score is less than 60,
                if record[2] < 60:
                    self.tableWidget_grade.setItem(rows, 3, QtWidgets.QTableWidgetItem("F"))
                # grade is D if score is between 60 and 69,
                elif record[2] >= 60 and record[2] < 70:
                    self.tableWidget_grade.setItem(rows, 3, QtWidgets.QTableWidgetItem("D"))
                # grade is C if score is between 70 and 79,
                elif record[2] >= 70 and record[2] < 80:
                    self.tableWidget_grade.setItem(rows, 3, QtWidgets.QTableWidgetItem("C"))
                # grade is B if score is between 80 and 89, and
                elif record[2] >= 80 and record[2] < 90:
                    self.tableWidget_grade.setItem(rows, 3, QtWidgets.QTableWidgetItem("B"))
                # grade is A between 90 and 100.
                else:
                    self.tableWidget_grade.setItem(rows, 3, QtWidgets.QTableWidgetItem("A"))


            self.close_connection()

        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not display to table" + str(e))
            msg.exec()

    # Button click event for Export data:
    def export_data(self):
        try:
            print("in the function export data")

            import json

            # create list to loop through rows to add and export to file
            data = []

            for rows in range(self.tableWidget_grade.rowCount()):
                id = self.tableWidget_grade.item(rows, 0).text()
                name = self.tableWidget_grade.item(rows, 1).text()
                score = self.tableWidget_grade.item(rows, 2).text()
                grade = self.tableWidget_grade.item(rows, 3).text()

                #add to list--> data
                data.append({"Student id":id, "Student Name" : name, "Student Score" : score, "Student Grade" : grade})

            # Write student id, name, score, and grade to an external file (studentgrades.json).
            # open file with intention to write
            with open("C:/Users/amryb/Desktop/ABP/NCSU/BUS 442/In class/studentgrades.json", "w") as file_handler:
                json.dump(data, file_handler)  # write student_data to opened file
            print("data exported")
            msg = QtWidgets.QMessageBox()
            msg.setText("Data exported successfully")
            msg.exec()

        except Exception as e:
            msg = QtWidgets.QMessageBox()
            msg.setText("Could not export data" + str(e))
            msg.exec()


if __name__ == '__main__':
    import sys
    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())