# Form implementation generated from reading ui file 'student_score.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_score = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_score.setGeometry(QtCore.QRect(100, 80, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_score.setFont(font)
        self.label_score.setObjectName("label_score")
        self.lineEdit_score = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_score.setGeometry(QtCore.QRect(240, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_score.setFont(font)
        self.lineEdit_score.setObjectName("lineEdit_score")
        self.pushButton_add_score = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_add_score.setGeometry(QtCore.QRect(130, 170, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_add_score.setFont(font)
        self.pushButton_add_score.setObjectName("pushButton_add_score")

        self.pushButton_add_score.clicked.connect(self.add_score)

        self.pushButton_avg_score = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_avg_score.setGeometry(QtCore.QRect(70, 230, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_avg_score.setFont(font)
        self.pushButton_avg_score.setObjectName("pushButton_avg_score")

        self.pushButton_avg_score.clicked.connect(self.avg_score)

        self.pushButton_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(160, 290, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.pushButton_clear.clicked.connect(self.clear)

        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(450, 70, 311, 261))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #list datastructure to
        self.student_scores = []

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_score.setText(_translate("MainWindow", "Student score"))
        self.pushButton_add_score.setText(_translate("MainWindow", "Add Score"))
        self.pushButton_avg_score.setText(_translate("MainWindow", "Calculate the average score"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Student Score"))
        self.listWidget.setSortingEnabled(__sortingEnabled)

    def clear(self):
        self.lineEdit_score.clear() #clears score line edit
        self.listWidget.clear() # clears data from the list widget
        self.student_scores.clear() #clears all orevious data from the list

    def add_score(self):
        #step 1:  validate user input
        if self.lineEdit_score.text().isdigit():
            self.listWidget.addItem(self.lineEdit_score.text())
            self.student_scores.append(float(self.lineEdit_score.text()))
            self.lineEdit_score.clear()
            self.lineEdit_score.setFocus()

        else: # not valid
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter a score")
            msg.exec()
            self.lineEdit_score.clear() # clear rhe input filed when the user input is invalid
            return None

    def avg_score(self):
        if len(self.student_scores) == 0:        # calculate the average
            msg = QtWidgets.QMessageBox()
            msg.setText("Please add student scores")
            msg.exec()
        else:
            total = sum(self.student_scores)    #sum of all the scores in the list
            count = len(self.student_scores)
            avg_score = total / count
            print(self.lineEdit_score.text(),total, count, avg_score)
            msg = QtWidgets.QMessageBox()
            msg.setText("Average student score:" + str(avg_score))
            msg.exec()



if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())