# Form implementation generated from reading ui file 'Student_add_update_delete.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 586)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 40, 371, 331))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_add = QtWidgets.QWidget()
        self.tab_add.setObjectName("tab_add")
        self.label_add_Id = QtWidgets.QLabel(parent=self.tab_add)
        self.label_add_Id.setGeometry(QtCore.QRect(30, 30, 61, 16))
        self.label_add_Id.setObjectName("label_add_Id")
        self.lineEdit_add_Id = QtWidgets.QLineEdit(parent=self.tab_add)
        self.lineEdit_add_Id.setGeometry(QtCore.QRect(100, 20, 151, 31))
        self.lineEdit_add_Id.setObjectName("lineEdit_add_Id")
        self.label_add_fname = QtWidgets.QLabel(parent=self.tab_add)
        self.label_add_fname.setGeometry(QtCore.QRect(30, 70, 61, 16))
        self.label_add_fname.setObjectName("label_add_fname")
        self.lineEdit_add_fname = QtWidgets.QLineEdit(parent=self.tab_add)
        self.lineEdit_add_fname.setGeometry(QtCore.QRect(100, 60, 151, 31))
        self.lineEdit_add_fname.setObjectName("lineEdit_add_fname")
        self.label_add_lname = QtWidgets.QLabel(parent=self.tab_add)
        self.label_add_lname.setGeometry(QtCore.QRect(30, 110, 61, 16))
        self.label_add_lname.setObjectName("label_add_lname")
        self.label_add_gpa = QtWidgets.QLabel(parent=self.tab_add)
        self.label_add_gpa.setGeometry(QtCore.QRect(30, 150, 61, 16))
        self.label_add_gpa.setObjectName("label_add_gpa")
        self.lineEdit_add_lname = QtWidgets.QLineEdit(parent=self.tab_add)
        self.lineEdit_add_lname.setGeometry(QtCore.QRect(100, 100, 151, 31))
        self.lineEdit_add_lname.setObjectName("lineEdit_add_lname")
        self.lineEdit_add_gpa = QtWidgets.QLineEdit(parent=self.tab_add)
        self.lineEdit_add_gpa.setGeometry(QtCore.QRect(100, 140, 151, 31))
        self.lineEdit_add_gpa.setObjectName("lineEdit_add_gpa")
        self.pushButton_add_clear = QtWidgets.QPushButton(parent=self.tab_add)
        self.pushButton_add_clear.setGeometry(QtCore.QRect(30, 240, 81, 31))
        self.pushButton_add_clear.setObjectName("pushButton_add_clear")

        self.pushButton_add_clear.clicked.connect(self.add_clear)

        self.pushButton_add_add = QtWidgets.QPushButton(parent=self.tab_add)
        self.pushButton_add_add.setGeometry(QtCore.QRect(160, 240, 91, 31))
        self.pushButton_add_add.setObjectName("pushButton_add_add")

        self.pushButton_add_add.clicked.connect(self.add_add_record)

        self.tabWidget.addTab(self.tab_add, "")
        self.tab_update = QtWidgets.QWidget()
        self.tab_update.setObjectName("tab_update")
        self.label_update_lname = QtWidgets.QLabel(parent=self.tab_update)
        self.label_update_lname.setGeometry(QtCore.QRect(40, 110, 61, 16))
        self.label_update_lname.setObjectName("label_update_lname")
        self.pushButton_update_add = QtWidgets.QPushButton(parent=self.tab_update)
        self.pushButton_update_add.setGeometry(QtCore.QRect(170, 240, 91, 31))
        self.pushButton_update_add.setObjectName("pushButton_update_add")

        #update the record after user clickes on the button
        self.pushButton_update_add.clicked.connect(self.update_update)

        self.lineEdit_update_fname = QtWidgets.QLineEdit(parent=self.tab_update)
        self.lineEdit_update_fname.setGeometry(QtCore.QRect(110, 60, 151, 31))
        self.lineEdit_update_fname.setObjectName("lineEdit_update_fname")
        self.lineEdit_update_lname = QtWidgets.QLineEdit(parent=self.tab_update)
        self.lineEdit_update_lname.setGeometry(QtCore.QRect(110, 100, 151, 31))
        self.lineEdit_update_lname.setObjectName("lineEdit_update_lname")
        self.label_update_Id = QtWidgets.QLabel(parent=self.tab_update)
        self.label_update_Id.setGeometry(QtCore.QRect(40, 30, 61, 16))
        self.label_update_Id.setObjectName("label_update_Id")
        self.lineEdit_update_Id = QtWidgets.QLineEdit(parent=self.tab_update)
        self.lineEdit_update_Id.setGeometry(QtCore.QRect(110, 20, 151, 31))
        self.lineEdit_update_Id.setObjectName("lineEdit_update_Id")
        self.label_update_fname = QtWidgets.QLabel(parent=self.tab_update)
        self.label_update_fname.setGeometry(QtCore.QRect(40, 70, 61, 16))
        self.label_update_fname.setObjectName("label_update_fname")
        self.label_update_gpa = QtWidgets.QLabel(parent=self.tab_update)
        self.label_update_gpa.setGeometry(QtCore.QRect(40, 150, 61, 16))
        self.label_update_gpa.setObjectName("label_update_gpa")
        self.pushButton_update_clear = QtWidgets.QPushButton(parent=self.tab_update)
        self.pushButton_update_clear.setGeometry(QtCore.QRect(40, 240, 81, 31))

        self.pushButton_update_clear.clicked.connect(self.update_clear)

        self.pushButton_update_clear.setObjectName("pushButton_update_clear")
        self.lineEdit_update_gpa = QtWidgets.QLineEdit(parent=self.tab_update)
        self.lineEdit_update_gpa.setGeometry(QtCore.QRect(110, 140, 151, 31))
        self.lineEdit_update_gpa.setObjectName("lineEdit_update_gpa")
        self.tabWidget.addTab(self.tab_update, "")
        self.tab_delete = QtWidgets.QWidget()
        self.tab_delete.setObjectName("tab_delete")
        self.pushButton_delete_clear = QtWidgets.QPushButton(parent=self.tab_delete)
        self.pushButton_delete_clear.setGeometry(QtCore.QRect(50, 240, 81, 31))
        self.pushButton_delete_clear.setObjectName("pushButton_delete_clear")

        self.pushButton_delete_clear.clicked.connect(self.delete_clear)

        self.pushButton_delete_add = QtWidgets.QPushButton(parent=self.tab_delete)
        self.pushButton_delete_add.setGeometry(QtCore.QRect(180, 240, 91, 31))

        self.pushButton_delete_add.clicked.connect(self.delete_delete)

        self.pushButton_delete_add.setObjectName("pushButton_delete_add")
        self.label_delete_Id = QtWidgets.QLabel(parent=self.tab_delete)
        self.label_delete_Id.setGeometry(QtCore.QRect(50, 30, 61, 16))
        self.label_delete_Id.setObjectName("label_delete_Id")
        self.lineEdit_delete_Id = QtWidgets.QLineEdit(parent=self.tab_delete)
        self.lineEdit_delete_Id.setGeometry(QtCore.QRect(120, 20, 151, 31))
        self.lineEdit_delete_Id.setObjectName("lineEdit_delete_Id")
        self.tabWidget.addTab(self.tab_delete, "")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(410, 60, 421, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 861, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        # dictonary to store data entered by the user using the UI form
        # update and delete stuudent record from the dictionary
        self.student_data = {}


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_add_Id.setText(_translate("MainWindow", "Student ID:"))
        self.label_add_fname.setText(_translate("MainWindow", "First Name:"))
        self.label_add_lname.setText(_translate("MainWindow", "Last Name:"))
        self.label_add_gpa.setText(_translate("MainWindow", "GPA:"))
        self.pushButton_add_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_add_add.setText(_translate("MainWindow", "Add Record"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_add), _translate("MainWindow", "Add Record"))
        self.label_update_lname.setText(_translate("MainWindow", "Last Name:"))
        self.pushButton_update_add.setText(_translate("MainWindow", "Update Record"))
        self.label_update_Id.setText(_translate("MainWindow", "Student ID:"))
        self.label_update_fname.setText(_translate("MainWindow", "First Name:"))
        self.label_update_gpa.setText(_translate("MainWindow", "GPA:"))
        self.pushButton_update_clear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_update), _translate("MainWindow", "Update Record"))
        self.pushButton_delete_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_delete_add.setText(_translate("MainWindow", "Delete Record"))
        self.label_delete_Id.setText(_translate("MainWindow", "Student ID:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_delete), _translate("MainWindow", "Delete Record"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Student ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Current GPA"))


    def add_clear(self):
        self.lineEdit_add_Id.clear()
        self.lineEdit_add_fname.clear()
        self.lineEdit_add_lname.clear()
        self.lineEdit_add_gpa.clear()

    def update_clear(self):
        self.lineEdit_update_Id.clear()
        self.lineEdit_update_fname.clear()
        self.lineEdit_update_lname.clear()
        self.lineEdit_update_gpa.clear()

    def delete_clear(self):
        self.lineEdit_delete_Id.clear()

    def add_add_record(self):
        if self.lineEdit_add_Id.text() not in self.student_data:    #add record if student data does not exist
            #self.student_data[key] = value <-- setup
            self.student_data[self.lineEdit_add_Id.text()] = {} # using the student id, create a dictionary to store id, fname, lname, gpa
            print(self.student_data)

            self.student_data[self.lineEdit_add_Id.text()]['id'] = self.lineEdit_add_Id.text()
            self.student_data[self.lineEdit_add_Id.text()]['fname'] = self.lineEdit_add_fname.text()
            self.student_data[self.lineEdit_add_Id.text()]['lname'] = self.lineEdit_add_lname.text()
            self.student_data[self.lineEdit_add_Id.text()]['gpa'] = self.lineEdit_add_gpa.text()
            print(self.student_data)

            #clear all input after accepting user input
            self.add_clear()
            #call the function to display data in the table
            self.display_data()

        else:
            msg = QtWidgets.QMessageBox()
            msg.setText("Student record Already Exist")
            msg.exec()
            self.add_clear()

    def update_update(self):
        #update record only if the record exists
        if self.lineEdit_add_Id.text() in self.student_data:
            self.student_data[self.lineEdit_add_Id.text()]['id'] = self.lineEdit_add_Id.text()
            self.student_data[self.lineEdit_add_Id.text()]['fname'] = self.lineEdit_add_fname.text()
            self.student_data[self.lineEdit_add_Id.text()]['lname'] = self.lineEdit_add_lname.text()
            self.student_data[self.lineEdit_add_Id.text()]['gpa'] = self.lineEdit_add_gpa.text()
            print(self.student_data)

            self.update_clear()

            self.display_data()

    def delete_delete(self):
        if self.lineEdit_delete_Id.text() in self.student_data:
            del self.student_data[self.lineEdit_delete_Id.text()]

            self.delete_clear()

        else:
            msg = QtWidgets.QMessageBox()
            msg.setText("Student record does not exist")
            msg.exec()

    def display_data(self):
        self.tableWidget.setRowCount(0)
        for id, record in self.student_data.items():
            print(id, record)
            print(record['id'],record['fname'], record['lname'], record['gpa'])

            row = self.tableWidget.rowCount()
            self.tableWidget.insertRow(row)

            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(record['id']))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(record['fname']))
            self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(record['lname']))
            self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(record['gpa']))


if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())