# Form implementation generated from reading ui file 'training_heart_rate.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_age = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_age.setGeometry(QtCore.QRect(130, 71, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_age.setFont(font)
        self.label_age.setObjectName("label_age")
        self.lineEdit_age = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_age.setGeometry(QtCore.QRect(290, 61, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_age.setFont(font)
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.label_resting_rate = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_resting_rate.setGeometry(QtCore.QRect(130, 131, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_resting_rate.setFont(font)
        self.label_resting_rate.setObjectName("label_resting_rate")
        self.lineEdit_resting_rate = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_resting_rate.setGeometry(QtCore.QRect(290, 120, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_resting_rate.setFont(font)
        self.lineEdit_resting_rate.setObjectName("lineEdit_resting_rate")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 240, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        #
        self.pushButton.clicked.connect(self.calculate_training_rate)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_age.setText(_translate("MainWindow", "Age"))
        self.label_resting_rate.setText(_translate("MainWindow", "Resting Rate"))
        self.pushButton.setText(_translate("MainWindow", "Calculate Training Rate"))


    def greetings(self):
        from datetime import datetime
        current_time = datetime.now()
        current_hour = current_time.hour

        if current_hour < 12:
            return "Good morning"
        elif current_hour == 12 and current_hour < 17:
            return "Good afternoon"
        else:
            return "Good evening"

    def  get_training_rate(self, age, resting_rate):
        training_rate = 0.6*(220 - age - resting_rate) + resting_rate
        return training_rate

    def calculate_training_rate(self):
        #step 1 --> identify the right greetings -- morning, afternoon, or evening
        get_greetings = self.greetings()

        #step 2: accept user's input
        self.age =  int(self.lineEdit_age.text())
        self.resting_rate = int(self.lineEdit_resting_rate.text())
        training_rate = self.get_training_rate(self.age, self.resting_rate)
        print(get_greetings, training_rate)

        msg = QtWidgets.QMessageBox()
        msg.setText(get_greetings +  "Your training heart rate is: " + str(training_rate))
        msg.exec()




if __name__ == '__main__':
    import sys

    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())