# Form implementation generated from reading ui file 'Unity_id.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QPushButton


class Ui_MainWindow(object):
    def __init__(self):
        self.pushButtin_generate_unity_id = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_first_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_first_name.setGeometry(QtCore.QRect(140, 90, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_first_name.setFont(font)
        self.label_first_name.setObjectName("label_first_name")
        self.lineEdit_first_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_first_name.setGeometry(QtCore.QRect(290, 90, 191, 41))
        self.lineEdit_first_name.setObjectName("lineEdit_first_name")
        self.label_middle_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_middle_name.setGeometry(QtCore.QRect(140, 160, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_middle_name.setFont(font)
        self.label_middle_name.setObjectName("label_middle_name")
        self.label_last_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_last_name.setGeometry(QtCore.QRect(140, 230, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_last_name.setFont(font)
        self.label_last_name.setObjectName("label_last_name")
        self.lineEdit_middle_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_middle_name.setGeometry(QtCore.QRect(290, 160, 191, 41))
        self.lineEdit_middle_name.setObjectName("lineEdit_middle_name")
        self.lineEdit_last_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_last_name.setGeometry(QtCore.QRect(290, 230, 191, 41))
        self.lineEdit_last_name.setObjectName("lineEdit_last_name")
        self.pushButton_generate_unity_id = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_generate_unity_id.setGeometry(QtCore.QRect(80, 320, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_generate_unity_id.setFont(font)
        self.pushButton_generate_unity_id.setObjectName("pushButton_generate_unity_id")

        #code when the user clicks on the "Generate UNITY ID" button
        self.pushButton_generate_unity_id.clicked.connect(self.generate_unity)

        self.pushButton_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(360, 320, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")

        # create the function self.clear to the button; code where the input is cleared
        self.pushButton_clear.clicked.connect(self.clear)

        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(570, 320, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")


        #creaete the function self.exit to exit from the code; code where the application is to exit
        self.pushButton_exit.clicked.connect(self.exit)


        self.label_unit_id = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_unit_id.setGeometry(QtCore.QRect(200, 450, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_unit_id.setFont(font)
        self.label_unit_id.setObjectName("label_unit_id")
        self.label_unity_id_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_unity_id_display.setGeometry(QtCore.QRect(340, 450, 211, 51))
        self.label_unity_id_display.setText("")
        self.label_unity_id_display.setObjectName("label_unity_id_display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_first_name.setText(_translate("MainWindow", "First Name"))
        self.label_middle_name.setText(_translate("MainWindow", "Middle Name"))
        self.label_last_name.setText(_translate("MainWindow", "Last Name"))
        self.pushButton_generate_unity_id.setText(_translate("MainWindow", "Generate UNITY ID"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear "))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        self.label_unit_id.setText(_translate("MainWindow", "UNITY ID"))

    #function to clear the inputs
    def clear(self):
        self.lineEdit_first_name.clear()
        self.lineEdit_middle_name.clear()
        self.lineEdit_last_name.clear()
        self.label_unity_id_display.clear()

    #function to exit application
    def exit(self):
        application.exit()

    def generate_unity(self):
        # step 1 accept user input --> first, middle, last name
        first_name = self.lineEdit_first_name.text()
        middle_name = self.lineEdit_middle_name.text()
        last_name = self.lineEdit_last_name.text()
        print("Input from the user:", first_name, middle_name, last_name)

        first_name = first_name.lower().strip()
        middle_name = middle_name.lower().strip()
        last_name = last_name.lower().strip()
        print("Lowercase input:", first_name, middle_name, last_name)

        # the first index of first name
        # the first index of middle name
        # the range 6 of last name
        unity = first_name[0] + middle_name[0] + last_name[0:6]
        print("Generated Unity ID:", unity)

        #show the generated ID in the label
        self.label_unity_id_display.setText(unity)

if __name__ == '__main__':
    import sys
    application = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QMainWindow()
    user_interface = Ui_MainWindow()
    user_interface.setupUi(form)
    form.show()
    sys.exit(application.exec())